In [1]:
import pandas as pd
import numpy as np

data = pd.read_excel("../data/data.xlsx")
data = data.sample(20000).copy()

In [2]:
data.head()

,Название,Цена,Дата,Телефон,Оператор,Контактное лицо (автор объявления),Тип автора,Регион,Город,Метро/Район,...,Источник,lat,lng,Персона для контактов,Доп.параметры,URL,Ссылки на картинки,Регион мобильного телефона,Номер подменён,"Расстояние до метро, км"
90720,"Коммерческая земля в Московская область, Волок...",45603,2025-03-19 23:21:56,89151278012,Мобильные ТелеСистемы,ГИС Торги,Агентство,Московская область,Волоколамский муниципальный округ,NaN,...,cian.ru,56.194373,36.260946,NaN,Ед. измерения площади=сот.|Категория=Участок п...,https://www.cian.ru/rent/commercial/309857268,https://images.cdn-cian.ru/images/2322472437-1...,г. Москва и Московская область,да,неизвестно
52024,Помещение свободного назначения в Московская о...,200000,2025-06-30 12:21:44,89891989491,Мобильные ТелеСистемы,Анна Болгарина (Частный маклер),Агентство,Московская область,Чехов,NaN,...,cian.ru,55.146630,37.482484,NaN,Этаж=1|Этажность здания=2|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/319248874,https://images.cdn-cian.ru/images/nezhiloe-pom...,Краснодарский край,да,неизвестно
37956,"Склад в Московская область, Балашиха Заря мкр,...",300000,2025-08-05 14:23:40,89175419103,Мобильные ТелеСистемы,Татьяна Осинцева,Агентство,Московская область,Балашиха,Новокосино,...,cian.ru,55.758802,38.079414,NaN,Этаж=1|Этажность здания=1|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/320077925,https://images.cdn-cian.ru/images/sklad-zarya-...,г. Москва и Московская область,да,17.417
61048,Помещение свободного назначения в Московская о...,375000,2025-06-06 10:29:07,89230793492,не определен,недоступно,Частное лицо (фильтр),Московская область,Королев,Медведково,...,cian.ru,55.934618,37.873745,NaN,Этаж=2|Этажность здания=2|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/318455773,https://images.cdn-cian.ru/images/nezhiloe-pom...,не определен,да,25.667
107380,"Мега Белая Дача, прикасса Ашана, торговые мест...",80000,2025-02-11 12:22:13,89249117868,не определен,Азбука Фермы,Агентство,Московская область,Котельники,Котельники,...,avito.ru,55.653299,37.844217,NaN,Этаж=1|Тип объявления=Сдам|Вид объекта=Торгово...,https://www.avito.ru/kotelniki/kommercheskaya_...,https://20.img.avito.st/image/1/1.JC7mtLa5iMfQ...,не определен,да,2.5

In [3]:
data.isna().sum()

Название                                  8
Цена                                      0
Дата                                      0
Телефон                                   0
Оператор                                  0
Контактное лицо (автор объявления)       98
Тип автора                                0
Регион                                    0
Город                                     0
Метро/Район                           10581
Адрес                                  5076
Описание                                213
Тип объявления                            0
Категория1                                0
Категория2                                0
ID на сайте                               0
Источник                                  0
lat                                       0
lng                                       0
Персона для контактов                 20000
Доп.параметры                             0
URL                                       0
Ссылки на картинки                      307
Регион мобильного телефона                0
Номер подменён                            0
Расстояние до метро, км                   0
dtype: int64

In [4]:
data = data.dropna(subset=["Цена"])

In [5]:
data.columns

Index(['Название', 'Цена', 'Дата', 'Телефон', 'Оператор',
       'Контактное лицо (автор объявления)', 'Тип автора', 'Регион', 'Город',
       'Метро/Район', 'Адрес', 'Описание', 'Тип объявления', 'Категория1',
       'Категория2', 'ID на сайте', 'Источник', 'lat', 'lng',
       'Персона для контактов', 'Доп.параметры', 'URL', 'Ссылки на картинки',
       'Регион мобильного телефона', 'Номер подменён',
       'Расстояние до метро, км'],
      dtype='object')

In [6]:
data[['Тип объявления', 'Категория1', 'Категория2']].nunique()

Тип объявления    1
Категория1        1
Категория2        1
dtype: int64

In [7]:
data = data.drop([
    'Телефон', 'Оператор', 'Контактное лицо (автор объявления)', 'Персона для контактов',
    'Номер подменён', 'Регион мобильного телефона', 'Регион',
    'Тип объявления', 'Категория1', 'Категория2',
], axis=1)

In [8]:
data.columns

Index(['Название', 'Цена', 'Дата', 'Тип автора', 'Город', 'Метро/Район',
       'Адрес', 'Описание', 'ID на сайте', 'Источник', 'lat', 'lng',
       'Доп.параметры', 'URL', 'Ссылки на картинки',
       'Расстояние до метро, км'],
      dtype='object')

In [9]:
data[['ID на сайте', 'Источник']]

        ID на сайте  Источник
90720     309857268   cian.ru
52024     319248874   cian.ru
37956     320077925   cian.ru
61048     318455773   cian.ru
107380   4719475341  avito.ru
...             ...       ...
132080    312146138   cian.ru
95478     314754992   cian.ru
23552     322604445   cian.ru
72855     317339233   cian.ru
130002    312330548   cian.ru

[20000 rows x 2 columns]

In [10]:
data = data.set_index(['ID на сайте', 'Источник'])

In [11]:
data

,,Название,Цена,Дата,Тип автора,Город,Метро/Район,Адрес,Описание,lat,lng,Доп.параметры,URL,Ссылки на картинки,"Расстояние до метро, км"
ID на сайте,Источник,,,,,,,,,,,,,,
309857268,cian.ru,"Коммерческая земля в Московская область, Волок...",45603,2025-03-19 23:21:56,Агентство,Волоколамский муниципальный округ,NaN,NaN,Данные получены с сайта ГИС Торги. Аренда земе...,56.194373,36.260946,Ед. измерения площади=сот.|Категория=Участок п...,https://www.cian.ru/rent/commercial/309857268,https://images.cdn-cian.ru/images/2322472437-1...,неизвестно
319248874,cian.ru,Помещение свободного назначения в Московская о...,200000,2025-06-30 12:21:44,Агентство,Чехов,NaN,"ул. Чехова, 4с1",Сдается подвальное помещение в г. Чехов. Помещ...,55.146630,37.482484,Этаж=1|Этажность здания=2|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/319248874,https://images.cdn-cian.ru/images/nezhiloe-pom...,неизвестно
320077925,cian.ru,"Склад в Московская область, Балашиха Заря мкр,...",300000,2025-08-05 14:23:40,Агентство,Балашиха,Новокосино,"Заря мкр,","Сдается склад, отапливаемый, ангар. Отопление ...",55.758802,38.079414,Этаж=1|Этажность здания=1|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/320077925,https://images.cdn-cian.ru/images/sklad-zarya-...,17.417
318455773,cian.ru,Помещение свободного назначения в Московская о...,375000,2025-06-06 10:29:07,Частное лицо (фильтр),Королев,Медведково,"Первомайский мкр, ул. Кирова, 2",Локация 260кв м (2й этаж) + отдельный вход Яко...,55.934618,37.873745,Этаж=2|Этажность здания=2|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/318455773,https://images.cdn-cian.ru/images/nezhiloe-pom...,25.667
4719475341,avito.ru,"Мега Белая Дача, прикасса Ашана, торговые мест...",80000,2025-02-11 12:22:13,Агентство,Котельники,Котельники,"Московская обл., Котельники, 1-й Покровский пр...","Mега Белaя Дaчa, пpикассовaя зонa Ашанa.Прeдлa...",55.653299,37.844217,Этаж=1|Тип объявления=Сдам|Вид объекта=Торгово...,https://www.avito.ru/kotelniki/kommercheskaya_...,https://20.img.avito.st/image/1/1.JC7mtLa5iMfQ...,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312146138,cian.ru,"Коммерческая земля в Московская область, Рузск...",14788,2025-01-12 19:22:16,Агентство,Рузский муниципальный округ,NaN,NaN,Дата начала аукциона: 05.02.2025 09:00 Размер ...,55.868703,36.449902,Ед. измерения площади=сот.|Категория=Участок п...,https://www.cian.ru/rent/commercial/312146138,https://images.cdn-cian.ru/images/2369728844-1...,неизвестно
314754992,cian.ru,"Коммерческая земля в Московская область, Щелко...",140513,2025-03-11 01:24:14,Агентство,Щелково,NaN,NaN,Дата начала аукциона: 04.04.2025 09:00 Размер ...,55.918949,38.027034,Ед. измерения площади=сот.|Категория=Промназна...,https://www.cian.ru/rent/commercial/314754992,NaN,неизвестно
322604445,cian.ru,Помещение свободного назначения в Московская о...,420000,2025-10-06 14:25:52,Агентство,Химки,Беломорская,"Рабочая ул., 2Ак5",Сдаётся просторное помещение свободного назнач...,55.908444,37.433409,Этаж=3|Этажность здания=7|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/322604445,https://images.cdn-cian.ru/images/nezhiloe-pom...,9.167
317339233,cian.ru,"Офис в Московская область, Жуковский ул. Гагар...",19725,2025-05-10 18:33:39,Агентство,Жуковский,Отдых,"ул. Гагарина, 2",Сдается офис на 4 этаже в административном зда...,55.598441,38.112589,Этаж=4|Этажность здания=4|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/317339233,https://images.cdn-cian.ru/images/ofis-zhukovs...,1.75
312330548,cian.ru,"Коммерческая земля в Московская область, Рузск...",9333,2025-01-15 03:23:42,Агентство,Рузский городской округ,NaN,NaN,Дата начала аукциона: 05.02.2025 09:00 Размер ...,55.862641,36.317696,Ед. измерения площади=сот.|Категория=Участок п...,https://www.cian.ru/rent/commercial/312330548,https://images.cdn-cian.ru/images/2373594028-1...,неизвестно

In [12]:
# data.loc[(313517556, "cian.ru")]

In [13]:
data[["Название", "Описание"]]

,,Название,Описание
ID на сайте,Источник,,
309857268,cian.ru,"Коммерческая земля в Московская область, Волок...",Данные получены с сайта ГИС Торги. Аренда земе...
319248874,cian.ru,Помещение свободного назначения в Московская о...,Сдается подвальное помещение в г. Чехов. Помещ...
320077925,cian.ru,"Склад в Московская область, Балашиха Заря мкр,...","Сдается склад, отапливаемый, ангар. Отопление ..."
318455773,cian.ru,Помещение свободного назначения в Московская о...,Локация 260кв м (2й этаж) + отдельный вход Яко...
4719475341,avito.ru,"Мега Белая Дача, прикасса Ашана, торговые мест...","Mега Белaя Дaчa, пpикассовaя зонa Ашанa.Прeдлa..."
...,...,...,...
312146138,cian.ru,"Коммерческая земля в Московская область, Рузск...",Дата начала аукциона: 05.02.2025 09:00 Размер ...
314754992,cian.ru,"Коммерческая земля в Московская область, Щелко...",Дата начала аукциона: 04.04.2025 09:00 Размер ...
322604445,cian.ru,Помещение свободного назначения в Московская о...,Сдаётся просторное помещение свободного назнач...
317339233,cian.ru,"Офис в Московская область, Жуковский ул. Гагар...",Сдается офис на 4 этаже в административном зда...
312330548,cian.ru,"Коммерческая земля в Московская область, Рузск...",Дата начала аукциона: 05.02.2025 09:00 Размер ...

In [14]:
data.loc[:, ["Название", "Описание"]]

,,Название,Описание
ID на сайте,Источник,,
309857268,cian.ru,"Коммерческая земля в Московская область, Волок...",Данные получены с сайта ГИС Торги. Аренда земе...
319248874,cian.ru,Помещение свободного назначения в Московская о...,Сдается подвальное помещение в г. Чехов. Помещ...
320077925,cian.ru,"Склад в Московская область, Балашиха Заря мкр,...","Сдается склад, отапливаемый, ангар. Отопление ..."
318455773,cian.ru,Помещение свободного назначения в Московская о...,Локация 260кв м (2й этаж) + отдельный вход Яко...
4719475341,avito.ru,"Мега Белая Дача, прикасса Ашана, торговые мест...","Mега Белaя Дaчa, пpикассовaя зонa Ашанa.Прeдлa..."
...,...,...,...
312146138,cian.ru,"Коммерческая земля в Московская область, Рузск...",Дата начала аукциона: 05.02.2025 09:00 Размер ...
314754992,cian.ru,"Коммерческая земля в Московская область, Щелко...",Дата начала аукциона: 04.04.2025 09:00 Размер ...
322604445,cian.ru,Помещение свободного назначения в Московская о...,Сдаётся просторное помещение свободного назнач...
317339233,cian.ru,"Офис в Московская область, Жуковский ул. Гагар...",Сдается офис на 4 этаже в административном зда...
312330548,cian.ru,"Коммерческая земля в Московская область, Рузск...",Дата начала аукциона: 05.02.2025 09:00 Размер ...

In [15]:
# data.loc[
#     (313517556, "cian.ru"),
#     "Описание",
# ]

In [16]:
data["Название"] = data["Название"].fillna("").astype(str)
data["Описание"] = data["Описание"].fillna("").astype(str)
data["Описание"] = "НАЗВАНИЕ: " + data["Название"] + "\n\n" + "ОПИСАНИЕ: " + data["Описание"]

In [17]:
# print(data.loc[
#     (313517556, "cian.ru"),
#     "Описание",
# ])

In [18]:
data = data.drop("Название", axis=1)

In [19]:
data["Доп.параметры"].iloc[10]

'Ед. измерения площади=сот.|Категория=Промназначение|Тип объявления=Сдам|Вид объекта=Коммерческая земля|Общая площадь=16.67'

In [20]:
def parse_parameters(v):
    return dict(
        pair.split("=")
        for pair in v.split("|")
    )

parse_parameters(data["Доп.параметры"].iloc[10])

{'Ед. измерения площади': 'сот.',
 'Категория': 'Промназначение',
 'Тип объявления': 'Сдам',
 'Вид объекта': 'Коммерческая земля',
 'Общая площадь': '16.67'}

In [21]:
_ = data["Доп.параметры"].apply(parse_parameters)
params_parsed = pd.json_normalize(_)
params_parsed.index = data.index
params_parsed

,,Ед. измерения площади,Категория,Тип объявления,Вид объекта,Общая площадь,Этаж,Этажность здания,Класс здания
ID на сайте,Источник,,,,,,,,
309857268,cian.ru,сот.,Участок поселений,Сдам,Коммерческая земля,23.75,NaN,NaN,NaN
319248874,cian.ru,NaN,NaN,Сдам,Помещение свободного назначения,313,1,2,NaN
320077925,cian.ru,NaN,NaN,Сдам,Складское помещение,300,1,1,NaN
318455773,cian.ru,NaN,NaN,Сдам,Помещение свободного назначения,250,2,2,NaN
4719475341,avito.ru,NaN,NaN,Сдам,Торговое помещение,14,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...
312146138,cian.ru,сот.,Участок поселений,Сдам,Коммерческая земля,15.0,NaN,NaN,NaN
314754992,cian.ru,сот.,Промназначение,Сдам,Коммерческая земля,12.13,NaN,NaN,NaN
322604445,cian.ru,NaN,NaN,Сдам,Помещение свободного назначения,1200,3,7,NaN
317339233,cian.ru,NaN,NaN,Сдам,Офисное помещение,26,4,4,NaN
312330548,cian.ru,сот.,Участок поселений,Сдам,Коммерческая земля,9.02,NaN,NaN,NaN

In [22]:
params_parsed.isna().sum() / params_parsed.shape[0] * 100

Ед. измерения площади    70.300
Категория                70.885
Тип объявления            0.000
Вид объекта               0.510
Общая площадь             0.010
Этаж                     31.245
Этажность здания         51.025
Класс здания             95.830
dtype: float64

In [23]:
params_parsed.nunique()

Ед. измерения площади       2
Категория                   3
Тип объявления              1
Вид объекта                 8
Общая площадь            4249
Этаж                       30
Этажность здания           46
Класс здания                4
dtype: int64

In [24]:
params_parsed["Ед. измерения площади"].unique()

array(['сот.', nan, 'га.'], dtype=object)

In [25]:
params_parsed = params_parsed.drop(["Класс здания", "Тип объявления"], axis=1)

In [26]:
data = pd.concat(
    [
        data.drop("Доп.параметры", axis=1),
        params_parsed
    ],
    axis=1
)
data

,,Цена,Дата,Тип автора,Город,Метро/Район,Адрес,Описание,lat,lng,URL,Ссылки на картинки,"Расстояние до метро, км",Ед. измерения площади,Категория,Вид объекта,Общая площадь,Этаж,Этажность здания
ID на сайте,Источник,,,,,,,,,,,,,,,,,,
309857268,cian.ru,45603,2025-03-19 23:21:56,Агентство,Волоколамский муниципальный округ,NaN,NaN,НАЗВАНИЕ: Коммерческая земля в Московская обла...,56.194373,36.260946,https://www.cian.ru/rent/commercial/309857268,https://images.cdn-cian.ru/images/2322472437-1...,неизвестно,сот.,Участок поселений,Коммерческая земля,23.75,NaN,NaN
319248874,cian.ru,200000,2025-06-30 12:21:44,Агентство,Чехов,NaN,"ул. Чехова, 4с1",НАЗВАНИЕ: Помещение свободного назначения в Мо...,55.146630,37.482484,https://www.cian.ru/rent/commercial/319248874,https://images.cdn-cian.ru/images/nezhiloe-pom...,неизвестно,NaN,NaN,Помещение свободного назначения,313,1,2
320077925,cian.ru,300000,2025-08-05 14:23:40,Агентство,Балашиха,Новокосино,"Заря мкр,","НАЗВАНИЕ: Склад в Московская область, Балашиха...",55.758802,38.079414,https://www.cian.ru/rent/commercial/320077925,https://images.cdn-cian.ru/images/sklad-zarya-...,17.417,NaN,NaN,Складское помещение,300,1,1
318455773,cian.ru,375000,2025-06-06 10:29:07,Частное лицо (фильтр),Королев,Медведково,"Первомайский мкр, ул. Кирова, 2",НАЗВАНИЕ: Помещение свободного назначения в Мо...,55.934618,37.873745,https://www.cian.ru/rent/commercial/318455773,https://images.cdn-cian.ru/images/nezhiloe-pom...,25.667,NaN,NaN,Помещение свободного назначения,250,2,2
4719475341,avito.ru,80000,2025-02-11 12:22:13,Агентство,Котельники,Котельники,"Московская обл., Котельники, 1-й Покровский пр...","НАЗВАНИЕ: Мега Белая Дача, прикасса Ашана, тор...",55.653299,37.844217,https://www.avito.ru/kotelniki/kommercheskaya_...,https://20.img.avito.st/image/1/1.JC7mtLa5iMfQ...,2.5,NaN,NaN,Торговое помещение,14,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312146138,cian.ru,14788,2025-01-12 19:22:16,Агентство,Рузский муниципальный округ,NaN,NaN,НАЗВАНИЕ: Коммерческая земля в Московская обла...,55.868703,36.449902,https://www.cian.ru/rent/commercial/312146138,https://images.cdn-cian.ru/images/2369728844-1...,неизвестно,сот.,Участок поселений,Коммерческая земля,15.0,NaN,NaN
314754992,cian.ru,140513,2025-03-11 01:24:14,Агентство,Щелково,NaN,NaN,НАЗВАНИЕ: Коммерческая земля в Московская обла...,55.918949,38.027034,https://www.cian.ru/rent/commercial/314754992,NaN,неизвестно,сот.,Промназначение,Коммерческая земля,12.13,NaN,NaN
322604445,cian.ru,420000,2025-10-06 14:25:52,Агентство,Химки,Беломорская,"Рабочая ул., 2Ак5",НАЗВАНИЕ: Помещение свободного назначения в Мо...,55.908444,37.433409,https://www.cian.ru/rent/commercial/322604445,https://images.cdn-cian.ru/images/nezhiloe-pom...,9.167,NaN,NaN,Помещение свободного назначения,1200,3,7
317339233,cian.ru,19725,2025-05-10 18:33:39,Агентство,Жуковский,Отдых,"ул. Гагарина, 2","НАЗВАНИЕ: Офис в Московская область, Жуковский...",55.598441,38.112589,https://www.cian.ru/rent/commercial/317339233,https://images.cdn-cian.ru/images/ofis-zhukovs...,1.75,NaN,NaN,Офисное помещение,26,4,4
312330548,cian.ru,9333,2025-01-15 03:23:42,Агентство,Рузский городской округ,NaN,NaN,НАЗВАНИЕ: Коммерческая земля в Московская обла...,55.862641,36.317696,https://www.cian.ru/rent/commercial/312330548,https://images.cdn-cian.ru/images/2373594028-1...,неизвестно,сот.,Участок поселений,Коммерческая земля,9.02,NaN,NaN

In [27]:
data.dtypes

Цена                         int64
Дата                        object
Тип автора                  object
Город                       object
Метро/Район                 object
Адрес                       object
Описание                    object
lat                        float64
lng                        float64
URL                         object
Ссылки на картинки          object
Расстояние до метро, км     object
Ед. измерения площади       object
Категория                   object
Вид объекта                 object
Общая площадь               object
Этаж                        object
Этажность здания            object
dtype: object

In [28]:
data["Категория"].unique()

array(['Участок поселений', nan, 'Сельхозназначение', 'Промназначение'],
      dtype=object)

In [29]:
data["Дата"] = pd.to_datetime(data["Дата"])
data["Дата"]

ID на сайте  Источник
309857268    cian.ru    2025-03-19 23:21:56
319248874    cian.ru    2025-06-30 12:21:44
320077925    cian.ru    2025-08-05 14:23:40
318455773    cian.ru    2025-06-06 10:29:07
4719475341   avito.ru   2025-02-11 12:22:13
                                ...
312146138    cian.ru    2025-01-12 19:22:16
314754992    cian.ru    2025-03-11 01:24:14
322604445    cian.ru    2025-10-06 14:25:52
317339233    cian.ru    2025-05-10 18:33:39
312330548    cian.ru    2025-01-15 03:23:42
Name: Дата, Length: 20000, dtype: datetime64[ns]

In [30]:
data["Дата"].dt.dayofyear

ID на сайте  Источник
309857268    cian.ru      78
319248874    cian.ru     181
320077925    cian.ru     217
318455773    cian.ru     157
4719475341   avito.ru     42
                        ...
312146138    cian.ru      12
314754992    cian.ru      70
322604445    cian.ru     279
317339233    cian.ru     130
312330548    cian.ru      15
Name: Дата, Length: 20000, dtype: int32

In [31]:
# data[[
#     "Расстояние до метро, км",
#     "Этаж",
#     "Общая площадь",
#     "Этажность здания",
# ]].astype(float)

In [32]:
data["Расстояние до метро, км"]

ID на сайте  Источник
309857268    cian.ru     неизвестно
319248874    cian.ru     неизвестно
320077925    cian.ru         17.417
318455773    cian.ru         25.667
4719475341   avito.ru           2.5
                            ...
312146138    cian.ru     неизвестно
314754992    cian.ru     неизвестно
322604445    cian.ru          9.167
317339233    cian.ru           1.75
312330548    cian.ru     неизвестно
Name: Расстояние до метро, км, Length: 20000, dtype: object

In [33]:
data["Расстояние до метро, км"] = data["Расстояние до метро, км"].replace({"неизвестно": np.nan}).values

C:\Users\Oleg\AppData\Local\Temp\ipykernel_11956\1761577118.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["Расстояние до метро, км"] = data["Расстояние до метро, км"].replace({"неизвестно": np.nan}).values

In [34]:
data[[
    "Расстояние до метро, км",
    "Этаж",
    "Общая площадь",
    "Этажность здания",
]] = data[[
    "Расстояние до метро, км",
    "Этаж",
    "Общая площадь",
    "Этажность здания",
]].astype(float)

In [35]:
data.isna().sum()

Цена                           0
Дата                           0
Тип автора                     0
Город                          0
Метро/Район                10581
Адрес                       5076
Описание                       0
lat                            0
lng                            0
URL                            0
Ссылки на картинки           307
Расстояние до метро, км    11397
Ед. измерения площади      14060
Категория                  14177
Вид объекта                  102
Общая площадь                  2
Этаж                        6249
Этажность здания           10205
dtype: int64

In [36]:
data["Ед. измерения площади"].value_counts()

Ед. измерения площади
сот.    5897
га.       43
Name: count, dtype: int64

In [37]:
data.dropna(subset=["Общая площадь", "Ед. измерения площади"])[["Общая площадь", "Ед. измерения площади"]]

                      Общая площадь Ед. измерения площади
ID на сайте Источник
309857268   cian.ru           23.75                  сот.
319196400   cian.ru            9.81                  сот.
312788323   cian.ru           14.68                  сот.
322703023   cian.ru           10.67                  сот.
312424495   cian.ru           16.67                  сот.
...                             ...                   ...
311829990   cian.ru           10.16                  сот.
318992646   cian.ru           10.02                  сот.
312146138   cian.ru           15.00                  сот.
314754992   cian.ru           12.13                  сот.
312330548   cian.ru            9.02                  сот.

[5940 rows x 2 columns]

In [38]:
data[["Общая площадь", "Ед. измерения площади"]].dropna()

                      Общая площадь Ед. измерения площади
ID на сайте Источник
309857268   cian.ru           23.75                  сот.
319196400   cian.ru            9.81                  сот.
312788323   cian.ru           14.68                  сот.
322703023   cian.ru           10.67                  сот.
312424495   cian.ru           16.67                  сот.
...                             ...                   ...
311829990   cian.ru           10.16                  сот.
318992646   cian.ru           10.02                  сот.
312146138   cian.ru           15.00                  сот.
314754992   cian.ru           12.13                  сот.
312330548   cian.ru            9.02                  сот.

[5940 rows x 2 columns]

In [39]:
data[["Общая площадь", "Ед. измерения площади"]].sample(5)

                      Общая площадь Ед. измерения площади
ID на сайте Источник
313427877   cian.ru           90.76                  сот.
313359566   cian.ru            8.08                  сот.
4519403001  avito.ru          52.40                   NaN
312837814   cian.ru           11.81                  сот.
318276609   cian.ru           10.16                  сот.

In [40]:
data.loc[
    data["Ед. измерения площади"] == "сот.",
    "Общая площадь"
] *= 100

data.loc[
    data["Ед. измерения площади"] == "га.",
    "Общая площадь"
] *= 10000

In [41]:
data = data.drop("Ед. измерения площади", axis=1)

In [43]:
# data.to_excel("../data/data_transformed.xlsx")