In [88]:
import pandas as pd
import numpy as np

data = pd.read_csv("../data/data_part3.csv")
data = data.sample(20000).copy()

In [89]:
data.head()

,Название,Цена,Дата,Телефон,Оператор,Контактное лицо (автор объявления),Тип автора,Регион,Город,Метро/Район,...,Источник,lat,lng,Персона для контактов,Доп.параметры,URL,Ссылки на картинки,Регион мобильного телефона,Номер подменён,"Расстояние до метро, км"
19203,"Склад в Московская область, Мытищи городской о...",1650000,2025-06-11 12:46:18,89921281045,не определен,CRE Department (HERZEN. Индустриальная Недвижи...,Агентство,Московская область,Мытищи городской округ,Лобня,...,cian.ru,56.023751,37.502022,NaN,Этаж=1|Этажность здания=1|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/318640420,https://images.cdn-cian.ru/images/2520883320-1...,не определен,да,5.5
201,Помещение свободного назначения в Московская о...,35000,2025-07-30 08:23:45,89863238002,не определен,Капитал Недвижимость,Агентство,Московская область,Химки,Беломорская,...,cian.ru,55.908444,37.433409,NaN,Этаж=3|Этажность здания=7|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/320032234,https://images.cdn-cian.ru/images/nezhiloe-pom...,не определен,да,9.167
9441,"Коммерческая земля в Московская область, Чехов...",85493,2025-07-06 02:24:32,89153135209,Мобильные ТелеСистемы,"Министерство инвестиций, промышленности и наук...",Агентство,Московская область,Чехов муниципальный округ,NaN,...,cian.ru,55.146462,37.300215,NaN,Ед. измерения площади=сот.|Категория=Сельхозна...,https://www.cian.ru/rent/commercial/319196407,https://images.cdn-cian.ru/images/2543367737-1...,г. Москва и Московская область,да,неизвестно
13870,"Свободного назначения, 9 м²",20700,2025-06-25 14:34:03,89675540522,МТТ,Михаил,Агентство,Московская область,Люберцы,Котельники,...,avito.ru,55.678056,37.865076,NaN,Этаж=1|Тип объявления=Сдам|Вид объекта=Помещен...,https://www.avito.ru/lyubertsy/kommercheskaya_...,https://80.img.avito.st/image/1/1._E03Ira5UKQB...,Свердловская область,да,0.60000002384186
10305,"Склад в Московская область, Раменский муниципа...",2333300,2025-07-04 00:24:47,89169577006,Мобильные ТелеСистемы,Отдел продаж INVEST 7 (INVEST7),Агентство,Московская область,Раменский муниципальный округ,Раменское,...,cian.ru,55.600979,38.462743,NaN,Этаж=1|Этажность здания=1|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/317908616,https://images.cdn-cian.ru/images/2499464006-1...,г. Москва и Московская область,да,26.583

In [90]:
data.isna().sum()

Название                                 82
Цена                                      0
Дата                                      0
Телефон                                   0
Оператор                                  0
Контактное лицо (автор объявления)       79
Тип автора                                0
Регион                                    0
Город                                     0
Метро/Район                            9329
Адрес                                  3339
Описание                                166
Тип объявления                            0
Категория1                                0
Категория2                                0
ID на сайте                               0
Источник                                  0
lat                                       0
lng                                       0
Персона для контактов                 20000
Доп.параметры                             0
URL                                       0
Ссылки на картинки                      504
Регион мобильного телефона                0
Номер подменён                            0
Расстояние до метро, км                   0
dtype: int64

In [91]:
data = data.dropna(subset=["Цена"])

In [92]:
data.columns

Index(['Название', 'Цена', 'Дата', 'Телефон', 'Оператор',
       'Контактное лицо (автор объявления)', 'Тип автора', 'Регион', 'Город',
       'Метро/Район', 'Адрес', 'Описание', 'Тип объявления', 'Категория1',
       'Категория2', 'ID на сайте', 'Источник', 'lat', 'lng',
       'Персона для контактов', 'Доп.параметры', 'URL', 'Ссылки на картинки',
       'Регион мобильного телефона', 'Номер подменён',
       'Расстояние до метро, км'],
      dtype='object')

In [93]:
data[['Тип объявления', 'Категория1', 'Категория2']].nunique()

Тип объявления    1
Категория1        1
Категория2        1
dtype: int64

In [94]:
data = data.drop([
    'Телефон', 'Оператор', 'Контактное лицо (автор объявления)', 'Персона для контактов',
    'Номер подменён', 'Регион мобильного телефона', 'Регион',
    'Тип объявления', 'Категория1', 'Категория2',
], axis=1)

In [95]:
data.columns

Index(['Название', 'Цена', 'Дата', 'Тип автора', 'Город', 'Метро/Район',
       'Адрес', 'Описание', 'ID на сайте', 'Источник', 'lat', 'lng',
       'Доп.параметры', 'URL', 'Ссылки на картинки',
       'Расстояние до метро, км'],
      dtype='object')

In [96]:
data[['ID на сайте', 'Источник']]

               ID на сайте          Источник
19203            318640420           cian.ru
201              320032234           cian.ru
9441             319196407           cian.ru
13870           7444423554          avito.ru
10305            317908616           cian.ru
...                    ...               ...
4601             318638090           cian.ru
18906  6195427078783590726  realty.yandex.ru
7765             319584400           cian.ru
6216             318852438           cian.ru
14101            318723476           cian.ru

[20000 rows x 2 columns]

In [97]:
data = data.set_index(['ID на сайте', 'Источник'])

In [98]:
data

,,Название,Цена,Дата,Тип автора,Город,Метро/Район,Адрес,Описание,lat,lng,Доп.параметры,URL,Ссылки на картинки,"Расстояние до метро, км"
ID на сайте,Источник,,,,,,,,,,,,,,
318640420,cian.ru,"Склад в Московская область, Мытищи городской о...",1650000,2025-06-11 12:46:18,Агентство,Мытищи городской округ,Лобня,NaN,Уникальный номер помещения - 9539-141. Аренда ...,56.023751,37.502022,Этаж=1|Этажность здания=1|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/318640420,https://images.cdn-cian.ru/images/2520883320-1...,5.5
320032234,cian.ru,Помещение свободного назначения в Московская о...,35000,2025-07-30 08:23:45,Агентство,Химки,Беломорская,"Рабочая ул., 2Ак5",Сдаётся просторное помещение свободного назнач...,55.908444,37.433409,Этаж=3|Этажность здания=7|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/320032234,https://images.cdn-cian.ru/images/nezhiloe-pom...,9.167
319196407,cian.ru,"Коммерческая земля в Московская область, Чехов...",85493,2025-07-06 02:24:32,Агентство,Чехов муниципальный округ,NaN,NaN,Дата начала аукциона: 11.07.2025 09:00 Размер ...,55.146462,37.300215,Ед. измерения площади=сот.|Категория=Сельхозна...,https://www.cian.ru/rent/commercial/319196407,https://images.cdn-cian.ru/images/2543367737-1...,неизвестно
7444423554,avito.ru,"Свободного назначения, 9 м²",20700,2025-06-25 14:34:03,Агентство,Люберцы,Котельники,"Московская обл., Люберцы, ул. Лётчика Ларюшина...",ЖК Жулебино парк. Летчика Ларюшина 6к1. Большо...,55.678056,37.865076,Этаж=1|Тип объявления=Сдам|Вид объекта=Помещен...,https://www.avito.ru/lyubertsy/kommercheskaya_...,https://80.img.avito.st/image/1/1._E03Ira5UKQB...,0.60000002384186
317908616,cian.ru,"Склад в Московская область, Раменский муниципа...",2333300,2025-07-04 00:24:47,Агентство,Раменский муниципальный округ,Раменское,"ул. Центральная, 1В",958442 . Склaдской комплeкс РФЗ в Раменскoм рa...,55.600979,38.462743,Этаж=1|Этажность здания=1|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/317908616,https://images.cdn-cian.ru/images/2499464006-1...,26.583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318638090,cian.ru,"Склад в Московская область, Клин Волоколамское...",9000000,2025-07-19 02:24:54,Агентство,Клин,NaN,"Волоколамское ш., 4",Услуги ответственного хранения. Уникальный ном...,56.331204,36.678842,Этаж=1|Этажность здания=1|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/318638090,https://images.cdn-cian.ru/images/2520800606-1...,неизвестно
6195427078783590726,realty.yandex.ru,Офис (386 м²),482499,2025-06-13 00:05:48,Агентство,Химки,Планерная,"улица Панфилова, 19с1",ПЛАТИМ ВОЗНАГРАЖДЕНИЕ 1) Пишите или звоните. ...,55.881490,37.432934,Этаж=3|Этажность здания=17|Тип объявления=Сдам...,https://realty.ya.ru/offer/6195427078783590726/,https://avatars.mds.yandex.net/get-realty-offe...,15.583
319584400,cian.ru,"Склад в Московская область, Ногинск Богородски...",7453420,2025-07-09 16:25:08,Агентство,Ногинск,NaN,"Богородский городской округ, Ногинск-Технопарк...",От Собственника. Предлагаю в долгосрочную арен...,55.826969,38.394364,Этаж=1|Этажность здания=1|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/319584400,https://images.cdn-cian.ru/images/2555791993-1...,неизвестно
318852438,cian.ru,"Склад в Московская область, Богородский городс...",222600,2025-07-14 18:25:20,Агентство,Богородский городской округ,Железнодорожная,"ул. Центральная, 14",Арт. 77185944 Производственно-складское помеще...,55.763918,38.234239,Этаж=1|Этажность здания=1|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/318852438,https://images.cdn-cian.ru/images/2528802544-1...,22
318723476,cian.ru,"Коммерческая земля в Московская область, Чехов...",61388,2025-06-25 02:36:47,Агентство,Чехов муниципальный округ,NaN,NaN,Дата начала аукциона: 09.07.2025 09:00 Размер ...,55.210033,37.574737,Ед. измерения площади=сот.|Категория=Сельхозна...,https://www.cian.ru/rent/commercial/318723476,https://images.cdn-cian.ru/images/2524014771-1...,неизвестно

In [99]:
# data.loc[(313517556, "cian.ru")]

In [100]:
data[["Название", "Описание"]]

,,Название,Описание
ID на сайте,Источник,,
318640420,cian.ru,"Склад в Московская область, Мытищи городской о...",Уникальный номер помещения - 9539-141. Аренда ...
320032234,cian.ru,Помещение свободного назначения в Московская о...,Сдаётся просторное помещение свободного назнач...
319196407,cian.ru,"Коммерческая земля в Московская область, Чехов...",Дата начала аукциона: 11.07.2025 09:00 Размер ...
7444423554,avito.ru,"Свободного назначения, 9 м²",ЖК Жулебино парк. Летчика Ларюшина 6к1. Большо...
317908616,cian.ru,"Склад в Московская область, Раменский муниципа...",958442 . Склaдской комплeкс РФЗ в Раменскoм рa...
...,...,...,...
318638090,cian.ru,"Склад в Московская область, Клин Волоколамское...",Услуги ответственного хранения. Уникальный ном...
6195427078783590726,realty.yandex.ru,Офис (386 м²),ПЛАТИМ ВОЗНАГРАЖДЕНИЕ 1) Пишите или звоните. ...
319584400,cian.ru,"Склад в Московская область, Ногинск Богородски...",От Собственника. Предлагаю в долгосрочную арен...
318852438,cian.ru,"Склад в Московская область, Богородский городс...",Арт. 77185944 Производственно-складское помеще...
318723476,cian.ru,"Коммерческая земля в Московская область, Чехов...",Дата начала аукциона: 09.07.2025 09:00 Размер ...

In [101]:
data.loc[:, ["Название", "Описание"]]

,,Название,Описание
ID на сайте,Источник,,
318640420,cian.ru,"Склад в Московская область, Мытищи городской о...",Уникальный номер помещения - 9539-141. Аренда ...
320032234,cian.ru,Помещение свободного назначения в Московская о...,Сдаётся просторное помещение свободного назнач...
319196407,cian.ru,"Коммерческая земля в Московская область, Чехов...",Дата начала аукциона: 11.07.2025 09:00 Размер ...
7444423554,avito.ru,"Свободного назначения, 9 м²",ЖК Жулебино парк. Летчика Ларюшина 6к1. Большо...
317908616,cian.ru,"Склад в Московская область, Раменский муниципа...",958442 . Склaдской комплeкс РФЗ в Раменскoм рa...
...,...,...,...
318638090,cian.ru,"Склад в Московская область, Клин Волоколамское...",Услуги ответственного хранения. Уникальный ном...
6195427078783590726,realty.yandex.ru,Офис (386 м²),ПЛАТИМ ВОЗНАГРАЖДЕНИЕ 1) Пишите или звоните. ...
319584400,cian.ru,"Склад в Московская область, Ногинск Богородски...",От Собственника. Предлагаю в долгосрочную арен...
318852438,cian.ru,"Склад в Московская область, Богородский городс...",Арт. 77185944 Производственно-складское помеще...
318723476,cian.ru,"Коммерческая земля в Московская область, Чехов...",Дата начала аукциона: 09.07.2025 09:00 Размер ...

In [102]:
# data.loc[
#     (313517556, "cian.ru"),
#     "Описание",
# ]

In [103]:
data["Название"] = data["Название"].fillna("").astype(str)
data["Описание"] = data["Описание"].fillna("").astype(str)
data["Описание"] = "НАЗВАНИЕ: " + data["Название"] + "\n\n" + "ОПИСАНИЕ: " + data["Описание"]

In [104]:
# print(data.loc[
#     (313517556, "cian.ru"),
#     "Описание",
# ])

In [105]:
data = data.drop("Название", axis=1)

In [106]:
data["Доп.параметры"].iloc[10]

'Ед. измерения площади=сот.|Категория=Промназначение|Тип объявления=Сдам|Вид объекта=Коммерческая земля|Общая площадь=56.92'

In [107]:
def parse_parameters(v):
    return dict(
        pair.split("=")
        for pair in v.split("|")
    )

parse_parameters(data["Доп.параметры"].iloc[10])

{'Ед. измерения площади': 'сот.',
 'Категория': 'Промназначение',
 'Тип объявления': 'Сдам',
 'Вид объекта': 'Коммерческая земля',
 'Общая площадь': '56.92'}

In [108]:
_ = data["Доп.параметры"].apply(parse_parameters)
params_parsed = pd.json_normalize(_)
params_parsed.index = data.index
params_parsed

,,Этаж,Этажность здания,Тип объявления,Вид объекта,Общая площадь,Ед. измерения площади,Категория,Класс здания
ID на сайте,Источник,,,,,,,,
318640420,cian.ru,1,1,Сдам,Складское помещение,1500,NaN,NaN,NaN
320032234,cian.ru,3,7,Сдам,Помещение свободного назначения,100,NaN,NaN,NaN
319196407,cian.ru,NaN,NaN,Сдам,Коммерческая земля,13.34,сот.,Сельхозназначение,NaN
7444423554,avito.ru,1,NaN,Сдам,Помещение свободного назначения,9,NaN,NaN,NaN
317908616,cian.ru,1,1,Сдам,Складское помещение,3500,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
318638090,cian.ru,1,1,Сдам,Складское помещение,10000,NaN,NaN,NaN
6195427078783590726,realty.yandex.ru,3,17,Сдам,Офисное помещение,386,NaN,NaN,NaN
319584400,cian.ru,1,1,Сдам,Складское помещение,5260,NaN,NaN,NaN
318852438,cian.ru,1,1,Сдам,Складское помещение,600,NaN,NaN,NaN
318723476,cian.ru,NaN,NaN,Сдам,Коммерческая земля,8.08,сот.,Сельхозназначение,NaN

In [109]:
params_parsed.isna().sum() / params_parsed.shape[0] * 100

Этаж                     21.080
Этажность здания         58.110
Тип объявления            0.000
Вид объекта               1.215
Общая площадь             0.055
Ед. измерения площади    80.455
Категория                80.995
Класс здания             92.535
dtype: float64

In [110]:
params_parsed.nunique()

Этаж                       32
Этажность здания           45
Тип объявления              1
Вид объекта                 8
Общая площадь            3654
Ед. измерения площади       2
Категория                   3
Класс здания                4
dtype: int64

In [111]:
params_parsed["Ед. измерения площади"].unique()

array([nan, 'сот.', 'га.'], dtype=object)

In [112]:
params_parsed = params_parsed.drop(["Класс здания", "Тип объявления"], axis=1)

In [113]:
data = pd.concat(
    [
        data.drop("Доп.параметры", axis=1),
        params_parsed
    ],
    axis=1
)
data

,,Цена,Дата,Тип автора,Город,Метро/Район,Адрес,Описание,lat,lng,URL,Ссылки на картинки,"Расстояние до метро, км",Этаж,Этажность здания,Вид объекта,Общая площадь,Ед. измерения площади,Категория
ID на сайте,Источник,,,,,,,,,,,,,,,,,,
318640420,cian.ru,1650000,2025-06-11 12:46:18,Агентство,Мытищи городской округ,Лобня,NaN,"НАЗВАНИЕ: Склад в Московская область, Мытищи г...",56.023751,37.502022,https://www.cian.ru/rent/commercial/318640420,https://images.cdn-cian.ru/images/2520883320-1...,5.5,1,1,Складское помещение,1500,NaN,NaN
320032234,cian.ru,35000,2025-07-30 08:23:45,Агентство,Химки,Беломорская,"Рабочая ул., 2Ак5",НАЗВАНИЕ: Помещение свободного назначения в Мо...,55.908444,37.433409,https://www.cian.ru/rent/commercial/320032234,https://images.cdn-cian.ru/images/nezhiloe-pom...,9.167,3,7,Помещение свободного назначения,100,NaN,NaN
319196407,cian.ru,85493,2025-07-06 02:24:32,Агентство,Чехов муниципальный округ,NaN,NaN,НАЗВАНИЕ: Коммерческая земля в Московская обла...,55.146462,37.300215,https://www.cian.ru/rent/commercial/319196407,https://images.cdn-cian.ru/images/2543367737-1...,неизвестно,NaN,NaN,Коммерческая земля,13.34,сот.,Сельхозназначение
7444423554,avito.ru,20700,2025-06-25 14:34:03,Агентство,Люберцы,Котельники,"Московская обл., Люберцы, ул. Лётчика Ларюшина...","НАЗВАНИЕ: Свободного назначения, 9 м²\n\nОПИСА...",55.678056,37.865076,https://www.avito.ru/lyubertsy/kommercheskaya_...,https://80.img.avito.st/image/1/1._E03Ira5UKQB...,0.60000002384186,1,NaN,Помещение свободного назначения,9,NaN,NaN
317908616,cian.ru,2333300,2025-07-04 00:24:47,Агентство,Раменский муниципальный округ,Раменское,"ул. Центральная, 1В","НАЗВАНИЕ: Склад в Московская область, Раменски...",55.600979,38.462743,https://www.cian.ru/rent/commercial/317908616,https://images.cdn-cian.ru/images/2499464006-1...,26.583,1,1,Складское помещение,3500,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318638090,cian.ru,9000000,2025-07-19 02:24:54,Агентство,Клин,NaN,"Волоколамское ш., 4","НАЗВАНИЕ: Склад в Московская область, Клин Вол...",56.331204,36.678842,https://www.cian.ru/rent/commercial/318638090,https://images.cdn-cian.ru/images/2520800606-1...,неизвестно,1,1,Складское помещение,10000,NaN,NaN
6195427078783590726,realty.yandex.ru,482499,2025-06-13 00:05:48,Агентство,Химки,Планерная,"улица Панфилова, 19с1",НАЗВАНИЕ: Офис (386 м²)\n\nОПИСАНИЕ: ПЛАТИМ ВО...,55.881490,37.432934,https://realty.ya.ru/offer/6195427078783590726/,https://avatars.mds.yandex.net/get-realty-offe...,15.583,3,17,Офисное помещение,386,NaN,NaN
319584400,cian.ru,7453420,2025-07-09 16:25:08,Агентство,Ногинск,NaN,"Богородский городской округ, Ногинск-Технопарк...","НАЗВАНИЕ: Склад в Московская область, Ногинск ...",55.826969,38.394364,https://www.cian.ru/rent/commercial/319584400,https://images.cdn-cian.ru/images/2555791993-1...,неизвестно,1,1,Складское помещение,5260,NaN,NaN
318852438,cian.ru,222600,2025-07-14 18:25:20,Агентство,Богородский городской округ,Железнодорожная,"ул. Центральная, 14","НАЗВАНИЕ: Склад в Московская область, Богородс...",55.763918,38.234239,https://www.cian.ru/rent/commercial/318852438,https://images.cdn-cian.ru/images/2528802544-1...,22,1,1,Складское помещение,600,NaN,NaN
318723476,cian.ru,61388,2025-06-25 02:36:47,Агентство,Чехов муниципальный округ,NaN,NaN,НАЗВАНИЕ: Коммерческая земля в Московская обла...,55.210033,37.574737,https://www.cian.ru/rent/commercial/318723476,https://images.cdn-cian.ru/images/2524014771-1...,неизвестно,NaN,NaN,Коммерческая земля,8.08,сот.,Сельхозназначение

In [114]:
data.dtypes

Цена                         int64
Дата                        object
Тип автора                  object
Город                       object
Метро/Район                 object
Адрес                       object
Описание                    object
lat                        float64
lng                        float64
URL                         object
Ссылки на картинки          object
Расстояние до метро, км     object
Этаж                        object
Этажность здания            object
Вид объекта                 object
Общая площадь               object
Ед. измерения площади       object
Категория                   object
dtype: object

In [115]:
data["Категория"].unique()

array([nan, 'Сельхозназначение', 'Участок поселений', 'Промназначение'],
      dtype=object)

In [116]:
data["Дата"] = pd.to_datetime(data["Дата"])
data["Дата"]

ID на сайте          Источник
318640420            cian.ru            2025-06-11 12:46:18
320032234            cian.ru            2025-07-30 08:23:45
319196407            cian.ru            2025-07-06 02:24:32
7444423554           avito.ru           2025-06-25 14:34:03
317908616            cian.ru            2025-07-04 00:24:47
                                                ...
318638090            cian.ru            2025-07-19 02:24:54
6195427078783590726  realty.yandex.ru   2025-06-13 00:05:48
319584400            cian.ru            2025-07-09 16:25:08
318852438            cian.ru            2025-07-14 18:25:20
318723476            cian.ru            2025-06-25 02:36:47
Name: Дата, Length: 20000, dtype: datetime64[ns]

In [117]:
data["Дата"].dt.dayofyear

ID на сайте          Источник
318640420            cian.ru             162
320032234            cian.ru             211
319196407            cian.ru             187
7444423554           avito.ru            176
317908616            cian.ru             185
                                        ...
318638090            cian.ru             200
6195427078783590726  realty.yandex.ru    164
319584400            cian.ru             190
318852438            cian.ru             195
318723476            cian.ru             176
Name: Дата, Length: 20000, dtype: int32

In [118]:
# data[[
#     "Расстояние до метро, км",
#     "Этаж",
#     "Общая площадь",
#     "Этажность здания",
# ]].astype(float)

In [119]:
data["Расстояние до метро, км"]

ID на сайте          Источник
318640420            cian.ru                          5.5
320032234            cian.ru                        9.167
319196407            cian.ru                   неизвестно
7444423554           avito.ru            0.60000002384186
317908616            cian.ru                       26.583
                                               ...
318638090            cian.ru                   неизвестно
6195427078783590726  realty.yandex.ru              15.583
319584400            cian.ru                   неизвестно
318852438            cian.ru                           22
318723476            cian.ru                   неизвестно
Name: Расстояние до метро, км, Length: 20000, dtype: object

In [120]:
data["Расстояние до метро, км"] = data["Расстояние до метро, км"].replace({"неизвестно": np.nan}).values

In [121]:
data[[
    "Расстояние до метро, км",
    "Этаж",
    "Общая площадь",
    "Этажность здания",
]] = data[[
    "Расстояние до метро, км",
    "Этаж",
    "Общая площадь",
    "Этажность здания",
]].astype(float)

In [122]:
data.isna().sum()

Цена                           0
Дата                           0
Тип автора                     0
Город                          0
Метро/Район                 9329
Адрес                       3339
Описание                       0
lat                            0
lng                            0
URL                            0
Ссылки на картинки           504
Расстояние до метро, км    10304
Этаж                        4216
Этажность здания           11622
Вид объекта                  243
Общая площадь                 11
Ед. измерения площади      16091
Категория                  16199
dtype: int64

In [123]:
data["Ед. измерения площади"].value_counts()

Ед. измерения площади
сот.    3858
га.       51
Name: count, dtype: int64

In [124]:
data.dropna(subset=["Общая площадь", "Ед. измерения площади"])[["Общая площадь", "Ед. измерения площади"]]

                      Общая площадь Ед. измерения площади
ID на сайте Источник
319196407   cian.ru           13.34                  сот.
319487008   cian.ru           14.00                  сот.
319366775   cian.ru           30.00                  сот.
318706285   cian.ru           20.93                  сот.
319557276   cian.ru           56.92                  сот.
...                             ...                   ...
319148778   cian.ru            2.30                  сот.
318871793   cian.ru           10.22                  сот.
318313209   cian.ru           61.52                  сот.
319153422   cian.ru            7.97                  сот.
318723476   cian.ru            8.08                  сот.

[3909 rows x 2 columns]

In [125]:
data[["Общая площадь", "Ед. измерения площади"]].dropna()

                      Общая площадь Ед. измерения площади
ID на сайте Источник
319196407   cian.ru           13.34                  сот.
319487008   cian.ru           14.00                  сот.
319366775   cian.ru           30.00                  сот.
318706285   cian.ru           20.93                  сот.
319557276   cian.ru           56.92                  сот.
...                             ...                   ...
319148778   cian.ru            2.30                  сот.
318871793   cian.ru           10.22                  сот.
318313209   cian.ru           61.52                  сот.
319153422   cian.ru            7.97                  сот.
318723476   cian.ru            8.08                  сот.

[3909 rows x 2 columns]

In [126]:
data[["Общая площадь", "Ед. измерения площади"]].sample(5)

                      Общая площадь Ед. измерения площади
ID на сайте Источник
7575564995  avito.ru          56.60                   NaN
7565199873  avito.ru         316.30                   NaN
318974130   cian.ru           14.18                  сот.
316223623   cian.ru           12.08                  сот.
319074136   cian.ru           16.27                  сот.

In [127]:
data.loc[
    data["Ед. измерения площади"] == "сот.",
    "Общая площадь"
] *= 100

data.loc[
    data["Ед. измерения площади"] == "га.",
    "Общая площадь"
] *= 10000

In [128]:
data = data.drop("Ед. измерения площади", axis=1)

In [129]:
data.to_csv("../data/data_transformed_part3.csv")