In [2]:
import pandas as pd
import numpy as np

In [16]:
df1 = pd.read_csv("../data/moscow_super_transformed.csv").set_index(['ID на сайте', 'Источник'])
df2 = pd.read_csv("../data/moscow_super_transformed_2.csv").set_index(['ID на сайте', 'Источник'])

In [17]:
df1[~df1.index.duplicated(keep='first')]

,,district_name,n_buildings_300m,n_living_buildings_300m,n_flats_300m,min_bc_distance_300m,mean_bc_distance_300m,traffic1_300m,traffic2_300m,traffic3_300m,traffic4_300m,...,Ветаптеки и ветклиники_600,Магазины цветов_600,"Прачечные, химчистки_600",Детские игровые залы_600,Религия_600,"Пиццерии, суши, столовые_600","Пекарни, кофейни_600","Кафе, бары, рестораны_600",Социальные_600,Банки_600
ID на сайте,Источник,,,,,,,,,,,,,,,,,,,,,
320731003,cian.ru,Зябликово,38.0,14.0,3610.0,0.0,123.500000,8176.0,6091.0,1557.0,1713.0,...,8.0,8.0,7.0,0.0,0.0,3.0,7.0,11.0,8.0,1.0
321876001,cian.ru,Хорошевский,54.0,15.0,1287.0,0.0,82.666667,9392.0,38428.0,1513.0,11424.0,...,3.0,12.0,9.0,0.0,0.0,10.0,34.0,30.0,5.0,2.0
322186790,cian.ru,Таганский,44.0,22.0,3234.0,9.0,178.200000,8304.0,19462.0,2032.0,6787.0,...,10.0,17.0,15.0,0.0,1.0,11.0,29.0,29.0,10.0,2.0
321392086,cian.ru,Бутово Южное,23.0,8.0,1831.0,10.0,10.000000,4194.0,4593.0,2101.0,3820.0,...,1.0,6.0,3.0,0.0,1.0,4.0,7.0,9.0,5.0,0.0
324943206,cian.ru,Останкинский,46.0,30.0,3647.0,4.0,117.000000,7146.0,24972.0,4008.0,17350.0,...,6.0,8.0,15.0,0.0,1.0,16.0,27.0,29.0,10.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7661472782,avito.ru,Бирюлево Восточное,34.0,11.0,4620.0,NaN,NaN,2510.0,1910.0,3910.0,3508.0,...,6.0,5.0,5.0,0.0,1.0,3.0,10.0,8.0,8.0,1.0
7661620373,avito.ru,Замоскворечье,116.0,25.0,1575.0,0.0,183.964286,732.0,14848.0,1211.0,6902.0,...,4.0,12.0,7.0,0.0,2.0,30.0,29.0,45.0,4.0,2.0
7661878835,avito.ru,Можайский,19.0,2.0,311.0,0.0,161.166667,1702.0,15748.0,108.0,8043.0,...,3.0,2.0,3.0,0.0,0.0,6.0,7.0,5.0,1.0,0.0
115650008171483504,realty.yandex.ru,Можайский,19.0,2.0,311.0,0.0,161.166667,1702.0,15748.0,108.0,8043.0,...,3.0,2.0,3.0,0.0,0.0,6.0,7.0,5.0,1.0,0.0
115650032134082800,realty.yandex.ru,Теплый Стан,22.0,11.0,1906.0,0.0,0.000000,370.0,12038.0,1590.0,5384.0,...,2.0,4.0,3.0,0.0,0.0,6.0,7.0,9.0,5.0,0.0

In [18]:
df = pd.concat([df1, df2], axis=0)
df

,,district_name,n_buildings_300m,n_living_buildings_300m,n_flats_300m,min_bc_distance_300m,mean_bc_distance_300m,traffic1_300m,traffic2_300m,traffic3_300m,traffic4_300m,...,Ветаптеки и ветклиники_600,Магазины цветов_600,"Прачечные, химчистки_600",Детские игровые залы_600,Религия_600,"Пиццерии, суши, столовые_600","Пекарни, кофейни_600","Кафе, бары, рестораны_600",Социальные_600,Банки_600
ID на сайте,Источник,,,,,,,,,,,,,,,,,,,,,
320731003,cian.ru,Зябликово,38.0,14.0,3610.0,0.0,123.500000,8176.0,6091.0,1557.0,1713.0,...,8.0,8.0,7.0,0.0,0.0,3.0,7.0,11.0,8.0,1.0
321876001,cian.ru,Хорошевский,54.0,15.0,1287.0,0.0,82.666667,9392.0,38428.0,1513.0,11424.0,...,3.0,12.0,9.0,0.0,0.0,10.0,34.0,30.0,5.0,2.0
322186790,cian.ru,Таганский,44.0,22.0,3234.0,9.0,178.200000,8304.0,19462.0,2032.0,6787.0,...,10.0,17.0,15.0,0.0,1.0,11.0,29.0,29.0,10.0,2.0
321392086,cian.ru,Бутово Южное,23.0,8.0,1831.0,10.0,10.000000,4194.0,4593.0,2101.0,3820.0,...,1.0,6.0,3.0,0.0,1.0,4.0,7.0,9.0,5.0,0.0
324943206,cian.ru,Останкинский,46.0,30.0,3647.0,4.0,117.000000,7146.0,24972.0,4008.0,17350.0,...,6.0,8.0,15.0,0.0,1.0,16.0,27.0,29.0,10.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324829822,cian.ru,Пресненский,21.0,8.0,1773.0,0.0,204.800000,4670.0,318598.0,5210.0,103583.0,...,7.0,32.0,16.0,2.0,1.0,50.0,93.0,152.0,1.0,13.0
324883207,cian.ru,Пресненский,21.0,8.0,1773.0,0.0,204.800000,4670.0,318598.0,5210.0,103583.0,...,7.0,32.0,16.0,2.0,1.0,50.0,93.0,152.0,1.0,13.0
322901132,cian.ru,Арбат,109.0,40.0,1004.0,3.0,160.400000,2296.0,13163.0,593.0,6700.0,...,3.0,15.0,14.0,3.0,8.0,15.0,55.0,102.0,6.0,2.0
3966105355551019008,realty.yandex.ru,Арбат,109.0,40.0,1004.0,3.0,160.266667,2296.0,13163.0,593.0,6700.0,...,3.0,15.0,14.0,3.0,8.0,15.0,55.0,102.0,6.0,2.0
323451346,cian.ru,Пресненский,12.0,3.0,137.0,0.0,163.583333,2956.0,139525.0,1665.0,105474.0,...,7.0,36.0,16.0,2.0,1.0,50.0,96.0,157.0,3.0,13.0

In [19]:
df_cleaned = df[~df.index.duplicated(keep='first')]
df_cleaned

,,district_name,n_buildings_300m,n_living_buildings_300m,n_flats_300m,min_bc_distance_300m,mean_bc_distance_300m,traffic1_300m,traffic2_300m,traffic3_300m,traffic4_300m,...,Ветаптеки и ветклиники_600,Магазины цветов_600,"Прачечные, химчистки_600",Детские игровые залы_600,Религия_600,"Пиццерии, суши, столовые_600","Пекарни, кофейни_600","Кафе, бары, рестораны_600",Социальные_600,Банки_600
ID на сайте,Источник,,,,,,,,,,,,,,,,,,,,,
320731003,cian.ru,Зябликово,38.0,14.0,3610.0,0.0,123.500000,8176.0,6091.0,1557.0,1713.0,...,8.0,8.0,7.0,0.0,0.0,3.0,7.0,11.0,8.0,1.0
321876001,cian.ru,Хорошевский,54.0,15.0,1287.0,0.0,82.666667,9392.0,38428.0,1513.0,11424.0,...,3.0,12.0,9.0,0.0,0.0,10.0,34.0,30.0,5.0,2.0
322186790,cian.ru,Таганский,44.0,22.0,3234.0,9.0,178.200000,8304.0,19462.0,2032.0,6787.0,...,10.0,17.0,15.0,0.0,1.0,11.0,29.0,29.0,10.0,2.0
321392086,cian.ru,Бутово Южное,23.0,8.0,1831.0,10.0,10.000000,4194.0,4593.0,2101.0,3820.0,...,1.0,6.0,3.0,0.0,1.0,4.0,7.0,9.0,5.0,0.0
324943206,cian.ru,Останкинский,46.0,30.0,3647.0,4.0,117.000000,7146.0,24972.0,4008.0,17350.0,...,6.0,8.0,15.0,0.0,1.0,16.0,27.0,29.0,10.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6033204199439718400,realty.yandex.ru,Пресненский,12.0,3.0,137.0,0.0,163.583333,2956.0,139525.0,1665.0,105474.0,...,7.0,36.0,16.0,2.0,1.0,50.0,96.0,157.0,3.0,13.0
3967137546321460224,realty.yandex.ru,Пресненский,12.0,3.0,137.0,0.0,163.583333,2956.0,139525.0,1665.0,105474.0,...,7.0,36.0,16.0,2.0,1.0,50.0,96.0,157.0,3.0,13.0
5888723453352094720,realty.yandex.ru,Пресненский,13.0,5.0,820.0,81.0,81.000000,6146.0,20551.0,0.0,0.0,...,2.0,10.0,4.0,0.0,0.0,6.0,10.0,21.0,9.0,1.0
2361989379596040192,realty.yandex.ru,Тверской,114.0,32.0,1806.0,73.0,194.000000,1464.0,22570.0,1183.0,15066.0,...,3.0,18.0,15.0,0.0,7.0,21.0,51.0,205.0,6.0,2.0
2459375922081150976,realty.yandex.ru,Мещанский,135.0,50.0,1538.0,4.0,187.562500,292.0,3493.0,515.0,8901.0,...,5.0,14.0,11.0,0.0,5.0,17.0,32.0,100.0,11.0,7.0

In [20]:
df_cleaned.to_csv("../data/moscow_super_transformed.csv")