In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv("../data/moscow_super_transformed.csv").set_index(['ID на сайте', 'Источник'])
df2 = pd.read_csv("../data/moscow_super_transformed_2.csv").set_index(['ID на сайте', 'Источник'])

In [3]:
df1

,,district_name,n_buildings_300m,n_living_buildings_300m,n_flats_300m,min_bc_distance_300m,mean_bc_distance_300m,traffic1_300m,traffic2_300m,traffic3_300m,traffic4_300m,...,Ветаптеки и ветклиники_600,Магазины цветов_600,"Прачечные, химчистки_600",Детские игровые залы_600,Религия_600,"Пиццерии, суши, столовые_600","Пекарни, кофейни_600","Кафе, бары, рестораны_600",Социальные_600,Банки_600
ID на сайте,Источник,,,,,,,,,,,,,,,,,,,,,
320731003,cian.ru,Зябликово,38.0,14.0,3610.0,0.0,123.500000,8176.0,6091.0,1557.0,1713.0,...,8,8,7,0,0,3,7,11,8,1
321876001,cian.ru,Хорошевский,54.0,15.0,1287.0,0.0,82.666667,9392.0,38428.0,1513.0,11424.0,...,3,12,9,0,0,10,34,30,5,2
322186790,cian.ru,Таганский,44.0,22.0,3234.0,9.0,178.200000,8304.0,19462.0,2032.0,6787.0,...,10,17,15,0,1,11,29,29,10,2
321392086,cian.ru,Бутово Южное,23.0,8.0,1831.0,10.0,10.000000,4194.0,4593.0,2101.0,3820.0,...,1,6,3,0,1,4,7,9,5,0
324943206,cian.ru,Останкинский,46.0,30.0,3647.0,4.0,117.000000,7146.0,24972.0,4008.0,17350.0,...,6,8,15,0,1,16,27,29,10,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2361989407165763072,realty.yandex.ru,Донской,47.0,15.0,1195.0,1.0,153.777778,992.0,29074.0,1856.0,12482.0,...,0,7,4,0,4,12,18,22,3,0
319013189,cian.ru,Марьина Роща,72.0,31.0,2836.0,52.0,148.000000,1014.0,7173.0,2167.0,11747.0,...,2,5,4,0,15,5,11,33,6,0
3966105355571245056,realty.yandex.ru,Обручевский,37.0,24.0,4805.0,174.0,231.500000,1604.0,15195.0,2387.0,2011.0,...,7,12,11,2,0,5,21,33,10,1
3986832478441152000,realty.yandex.ru,Филевский Парк,48.0,16.0,2926.0,5.0,188.882353,2332.0,25228.0,2885.0,12028.0,...,1,4,4,1,0,14,23,46,1,0
8660284132704650240,realty.yandex.ru,Даниловский,26.0,2.0,NaN,0.0,161.222222,5974.0,18918.0,993.0,20463.0,...,0,4,4,1,0,7,14,18,0,0

In [4]:
df2

,,district_name,n_buildings_300m,n_living_buildings_300m,n_flats_300m,min_bc_distance_300m,mean_bc_distance_300m,traffic1_300m,traffic2_300m,traffic3_300m,traffic4_300m,...,Ветаптеки и ветклиники_600,Магазины цветов_600,"Прачечные, химчистки_600",Детские игровые залы_600,Религия_600,"Пиццерии, суши, столовые_600","Пекарни, кофейни_600","Кафе, бары, рестораны_600",Социальные_600,Банки_600
ID на сайте,Источник,,,,,,,,,,,,,,,,,,,,,
2361982363910666240,realty.yandex.ru,Ломоносовский,39.0,25.0,2908.0,21.0,205.500000,904,14954,1522,16449,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324514270,cian.ru,Ломоносовский,40.0,26.0,3121.0,0.0,167.333333,904,14954,1522,16449,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323292280,cian.ru,Ломоносовский,40.0,26.0,3121.0,0.0,167.333333,904,14954,1522,16449,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319684273,cian.ru,Бибирево,32.0,15.0,3884.0,NaN,NaN,2052,2578,3431,2210,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3051474308312615936,realty.yandex.ru,Ломоносовский,39.0,25.0,2908.0,21.0,205.500000,904,14954,1522,16449,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324829822,cian.ru,Пресненский,21.0,8.0,1773.0,0.0,204.800000,4670,318598,5210,103583,...,7.0,32.0,16.0,2.0,1.0,50.0,93.0,152.0,1.0,13.0
324883207,cian.ru,Пресненский,21.0,8.0,1773.0,0.0,204.800000,4670,318598,5210,103583,...,7.0,32.0,16.0,2.0,1.0,50.0,93.0,152.0,1.0,13.0
322901132,cian.ru,Арбат,109.0,40.0,1004.0,3.0,160.400000,2296,13163,593,6700,...,3.0,15.0,14.0,3.0,8.0,15.0,55.0,102.0,6.0,2.0
3966105355551019008,realty.yandex.ru,Арбат,109.0,40.0,1004.0,3.0,160.266667,2296,13163,593,6700,...,3.0,15.0,14.0,3.0,8.0,15.0,55.0,102.0,6.0,2.0
323451346,cian.ru,Пресненский,12.0,3.0,137.0,0.0,163.583333,2956,139525,1665,105474,...,7.0,36.0,16.0,2.0,1.0,50.0,96.0,157.0,3.0,13.0

In [5]:
df = pd.concat([df1, df2], axis=0)
df

,,district_name,n_buildings_300m,n_living_buildings_300m,n_flats_300m,min_bc_distance_300m,mean_bc_distance_300m,traffic1_300m,traffic2_300m,traffic3_300m,traffic4_300m,...,Ветаптеки и ветклиники_600,Магазины цветов_600,"Прачечные, химчистки_600",Детские игровые залы_600,Религия_600,"Пиццерии, суши, столовые_600","Пекарни, кофейни_600","Кафе, бары, рестораны_600",Социальные_600,Банки_600
ID на сайте,Источник,,,,,,,,,,,,,,,,,,,,,
320731003,cian.ru,Зябликово,38.0,14.0,3610.0,0.0,123.500000,8176.0,6091.0,1557.0,1713.0,...,8.0,8.0,7.0,0.0,0.0,3.0,7.0,11.0,8.0,1.0
321876001,cian.ru,Хорошевский,54.0,15.0,1287.0,0.0,82.666667,9392.0,38428.0,1513.0,11424.0,...,3.0,12.0,9.0,0.0,0.0,10.0,34.0,30.0,5.0,2.0
322186790,cian.ru,Таганский,44.0,22.0,3234.0,9.0,178.200000,8304.0,19462.0,2032.0,6787.0,...,10.0,17.0,15.0,0.0,1.0,11.0,29.0,29.0,10.0,2.0
321392086,cian.ru,Бутово Южное,23.0,8.0,1831.0,10.0,10.000000,4194.0,4593.0,2101.0,3820.0,...,1.0,6.0,3.0,0.0,1.0,4.0,7.0,9.0,5.0,0.0
324943206,cian.ru,Останкинский,46.0,30.0,3647.0,4.0,117.000000,7146.0,24972.0,4008.0,17350.0,...,6.0,8.0,15.0,0.0,1.0,16.0,27.0,29.0,10.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324829822,cian.ru,Пресненский,21.0,8.0,1773.0,0.0,204.800000,4670.0,318598.0,5210.0,103583.0,...,7.0,32.0,16.0,2.0,1.0,50.0,93.0,152.0,1.0,13.0
324883207,cian.ru,Пресненский,21.0,8.0,1773.0,0.0,204.800000,4670.0,318598.0,5210.0,103583.0,...,7.0,32.0,16.0,2.0,1.0,50.0,93.0,152.0,1.0,13.0
322901132,cian.ru,Арбат,109.0,40.0,1004.0,3.0,160.400000,2296.0,13163.0,593.0,6700.0,...,3.0,15.0,14.0,3.0,8.0,15.0,55.0,102.0,6.0,2.0
3966105355551019008,realty.yandex.ru,Арбат,109.0,40.0,1004.0,3.0,160.266667,2296.0,13163.0,593.0,6700.0,...,3.0,15.0,14.0,3.0,8.0,15.0,55.0,102.0,6.0,2.0
323451346,cian.ru,Пресненский,12.0,3.0,137.0,0.0,163.583333,2956.0,139525.0,1665.0,105474.0,...,7.0,36.0,16.0,2.0,1.0,50.0,96.0,157.0,3.0,13.0

In [6]:
df_cleaned = df.drop_duplicates().copy()
df_cleaned

,,district_name,n_buildings_300m,n_living_buildings_300m,n_flats_300m,min_bc_distance_300m,mean_bc_distance_300m,traffic1_300m,traffic2_300m,traffic3_300m,traffic4_300m,...,Ветаптеки и ветклиники_600,Магазины цветов_600,"Прачечные, химчистки_600",Детские игровые залы_600,Религия_600,"Пиццерии, суши, столовые_600","Пекарни, кофейни_600","Кафе, бары, рестораны_600",Социальные_600,Банки_600
ID на сайте,Источник,,,,,,,,,,,,,,,,,,,,,
320731003,cian.ru,Зябликово,38.0,14.0,3610.0,0.0,123.500000,8176.0,6091.0,1557.0,1713.0,...,8.0,8.0,7.0,0.0,0.0,3.0,7.0,11.0,8.0,1.0
321876001,cian.ru,Хорошевский,54.0,15.0,1287.0,0.0,82.666667,9392.0,38428.0,1513.0,11424.0,...,3.0,12.0,9.0,0.0,0.0,10.0,34.0,30.0,5.0,2.0
322186790,cian.ru,Таганский,44.0,22.0,3234.0,9.0,178.200000,8304.0,19462.0,2032.0,6787.0,...,10.0,17.0,15.0,0.0,1.0,11.0,29.0,29.0,10.0,2.0
321392086,cian.ru,Бутово Южное,23.0,8.0,1831.0,10.0,10.000000,4194.0,4593.0,2101.0,3820.0,...,1.0,6.0,3.0,0.0,1.0,4.0,7.0,9.0,5.0,0.0
324943206,cian.ru,Останкинский,46.0,30.0,3647.0,4.0,117.000000,7146.0,24972.0,4008.0,17350.0,...,6.0,8.0,15.0,0.0,1.0,16.0,27.0,29.0,10.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323352679,cian.ru,Таганский,133.0,19.0,527.0,8.0,170.153846,2328.0,44067.0,738.0,11746.0,...,0.0,11.0,11.0,0.0,30.0,22.0,44.0,149.0,3.0,4.0
3786967450365862912,realty.yandex.ru,Пресненский,19.0,12.0,527.0,0.0,171.000000,1580.0,73525.0,786.0,18388.0,...,7.0,27.0,12.0,2.0,1.0,34.0,65.0,111.0,7.0,9.0
8660284132701755392,realty.yandex.ru,Мещанский,119.0,12.0,105.0,0.0,194.931034,544.0,25520.0,282.0,17933.0,...,2.0,20.0,22.0,3.0,11.0,28.0,88.0,269.0,11.0,4.0
3965285094530994176,realty.yandex.ru,Тверской,136.0,47.0,915.0,0.0,194.066667,604.0,6720.0,635.0,6296.0,...,6.0,18.0,17.0,0.0,15.0,28.0,49.0,180.0,12.0,5.0
3966105355551019008,realty.yandex.ru,Арбат,109.0,40.0,1004.0,3.0,160.266667,2296.0,13163.0,593.0,6700.0,...,3.0,15.0,14.0,3.0,8.0,15.0,55.0,102.0,6.0,2.0

In [9]:
df_cleaned.to_csv("../data/moscow_super_transformed.csv")