In [1]:
import pandas as pd
import numpy as np
import sklearn

df = pd.read_csv("../../data/data_transformed_main.csv").set_index(["ID на сайте","Источник"])

In [2]:
df

,,Цена,Дата,Тип автора,Город,Метро/Район,Адрес,Описание,lat,lng,URL,Ссылки на картинки,"Расстояние до метро, км",Этаж,Этажность здания,Вид объекта,Общая площадь,Цена / м2,Москва?
ID на сайте,Источник,,,,,,,,,,,,,,,,,,
321970859,cian.ru,34500.0,2025-12-17 08:36:40,Агентство,Химки,Беломорская,"Рабочая ул., 2","НАЗВАНИЕ: Офис в Московская область, Химки Раб...",55.908036,37.432951,https://www.cian.ru/rent/commercial/321970859,https://images.cdn-cian.ru/images/2633983674-1...,9.167,4.0,4.0,Офис / Здание,23.0,1500.000000,0.0
323570959,cian.ru,160500.0,2025-12-17 08:36:40,Частное лицо,Солнечногорск городской округ,Зеленоград — Крюково,21А,НАЗВАНИЕ: Торговая площадь в Московская област...,55.972650,37.099604,https://www.cian.ru/rent/commercial/323570959,https://images.cdn-cian.ru/images/torgovoe-pom...,9.167,1.0,1.0,Торговое / свободного вида,107.0,1500.000000,0.0
319937619,cian.ru,1226740.0,2025-12-17 08:36:40,Агентство,Мытищи,Медведково,"ул. Колпакова, 46А","НАЗВАНИЕ: Офис в Московская область, Мытищи ул...",55.925178,37.718300,https://www.cian.ru/rent/commercial/319937619,https://images.cdn-cian.ru/images/2634163777-1...,9.167,2.0,6.0,Офис / Здание,830.0,1478.000000,0.0
319936797,cian.ru,236480.0,2025-12-17 08:36:39,Агентство,Мытищи,Медведково,"ул. Колпакова, 46А","НАЗВАНИЕ: Офис в Московская область, Мытищи ул...",55.925178,37.718300,https://www.cian.ru/rent/commercial/319936797,https://images.cdn-cian.ru/images/2634163921-1...,9.167,2.0,6.0,Офис / Здание,160.0,1478.000000,0.0
319938233,cian.ru,1537120.0,2025-12-17 08:36:38,Агентство,Мытищи,Медведково,"ул. Колпакова, 46А","НАЗВАНИЕ: Офис в Московская область, Мытищи ул...",55.925178,37.718300,https://www.cian.ru/rent/commercial/319938233,https://images.cdn-cian.ru/images/2569099478-1...,9.167,2.0,6.0,Офис / Здание,1040.0,1478.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4750280767,avito.ru,736325.0,2025-02-28 14:19:30,Агентство,Химки,Химки,"Московская обл., Химки, ул. Панфилова, 19с1",НАЗВАНИЕ: Офисное помещение 516.12 кв.м от соб...,55.881490,37.432933,https://www.avito.ru/himki/kommercheskaya_nedv...,https://30.img.avito.st/image/1/1.AlU-sba5rrwI...,1.900,1.0,NaN,Офис/Здание,516.1,1426.709940,0.0
4750437026,avito.ru,270000.0,2025-02-28 14:19:23,Агентство,Котельники,Котельники,"Московская обл., Котельники, Дзержинское ш., 2",НАЗВАНИЕ: Офисное помещение 182.24 кв.м от соб...,55.654477,37.856443,https://www.avito.ru/kotelniki/kommercheskaya_...,https://10.img.avito.st/image/1/1.xz3K9La5a9T8...,2.200,5.0,NaN,Офис/Здание,182.2,1481.888035,0.0
4750004434,avito.ru,743442.0,2025-02-28 14:19:06,Агентство,Химки,Химки,"Московская обл., Химки, ул. Панфилова, 19с1",НАЗВАНИЕ: Офисное помещение 521 кв.м от собств...,55.881490,37.432933,https://www.avito.ru/himki/kommercheskaya_nedv...,https://70.img.avito.st/image/1/1.y5athra5Z3-b...,1.900,1.0,NaN,Офис/Здание,521.0,1426.952015,0.0
4749580770,avito.ru,226184.0,2025-02-28 14:18:41,Агентство,Химки,NaN,"Московская обл., Химки, Авиационная ул., 8",НАЗВАНИЕ: Офисное помещение 232.7 кв.м от собс...,55.983494,37.408939,https://www.avito.ru/himki/kommercheskaya_nedv...,https://10.img.avito.st/image/1/1.DYLprra5oWvf...,NaN,2.0,NaN,Офис/Здание,232.7,971.998281,0.0
4937488939,avito.ru,37500.0,2025-02-28 14:10:16,Агентство,Лобня,Лобня,"Московская обл., Лобня, ул. Ленина, 19к1","НАЗВАНИЕ: Торговое помещение на трафике, 106 м...",56.011696,37.478531,https://www.avito.ru/lobnya/kommercheskaya_ned...,https://70.img.avito.st/image/1/1.gf5Imra5LRd-...,0.400,1.0,NaN,Торговое/Свободного назначения,106.0,4245.283019,0.0

In [3]:
df["Вид объекта"].unique()

array(['Офис / Здание', 'Торговое / свободного вида',
       'Торговое / Свободного назначения',
       'Торговое / Свободное назначение',
       'Торговое/Свободного назначения', 'Офис/Здание'], dtype=object)

In [4]:
df["Вид объекта"] = df["Вид объекта"].replace({'Торговое / свободного вида' : 'Торговое / Свободного назначения','Торговое / Свободное назначение': 'Торговое / Свободного назначения',
               'Торговое/Свободного назначения': 'Торговое / Свободного назначения', 'Офис/Здание': 'Офис / Здание'})
df["Москва?"] = df["Москва?"].replace({'False':0.0, 'True':1.0})
df["Москва?"].unique()

array(['0.0', '1.0', 0.0, 1.0], dtype=object)

In [5]:
df["Вид объекта"].unique()

array(['Офис / Здание', 'Торговое / Свободного назначения'], dtype=object)

In [6]:
df.groupby("Вид объекта")["Цена"].mean()

Вид объекта
Офис / Здание                       496837.200929
Торговое / Свободного назначения    277255.474716
Name: Цена, dtype: float64

In [7]:
from sklearn.preprocessing import (
    OneHotEncoder, OrdinalEncoder, TargetEncoder,
    StandardScaler, MinMaxScaler, RobustScaler, )
from sklearn.linear_model import (
    LinearRegression, Ridge, Lasso, QuantileRegressor)
from sklearn.metrics import (
    r2_score,
    root_mean_squared_error as rmse,
    mean_absolute_percentage_error as mape,)
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
df.columns

Index(['Цена', 'Дата', 'Тип автора', 'Город', 'Метро/Район', 'Адрес',
       'Описание', 'lat', 'lng', 'URL', 'Ссылки на картинки',
       'Расстояние до метро, км', 'Этаж', 'Этажность здания', 'Вид объекта',
       'Общая площадь', 'Цена / м2', 'Москва?'],
      dtype='object')

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn import set_config
set_config(transform_output="pandas")

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
from sklearn import set_config
from sklearn.compose import ColumnTransformer

set_config(transform_output="pandas")

ct = ColumnTransformer(
    transformers=[
        ("scale", StandardScaler(), ["Общая площадь", "Расстояние до метро, км"]),
        ("onehot", OneHotEncoder(sparse_output=False), ["Вид объекта"]),
        ("ordinal", OrdinalEncoder(), ["Тип автора"]),
    ],
    remainder="passthrough",
    n_jobs=-1,
).set_output(transform="pandas")

ct.fit(df)

ColumnTransformer(n_jobs=-1, remainder='passthrough',
                  transformers=[('scale', StandardScaler(),
                                 ['Общая площадь', 'Расстояние до метро, км']),
                                ('onehot', OneHotEncoder(sparse_output=False),
                                 ['Вид объекта']),
                                ('ordinal', OrdinalEncoder(), ['Тип автора'])])

In [12]:
ct.transform(df)

,,scale__Общая площадь,"scale__Расстояние до метро, км",onehot__Вид объекта_Офис / Здание,onehot__Вид объекта_Торговое / Свободного назначения,ordinal__Тип автора,remainder__Цена,remainder__Дата,remainder__Город,remainder__Метро/Район,remainder__Адрес,remainder__Описание,remainder__lat,remainder__lng,remainder__URL,remainder__Ссылки на картинки,remainder__Этаж,remainder__Этажность здания,remainder__Цена / м2,remainder__Москва?
ID на сайте,Источник,,,,,,,,,,,,,,,,,,,
321970859,cian.ru,-0.727409,-0.071871,1.0,0.0,0.0,34500.0,2025-12-17 08:36:40,Химки,Беломорская,"Рабочая ул., 2","НАЗВАНИЕ: Офис в Московская область, Химки Раб...",55.908036,37.432951,https://www.cian.ru/rent/commercial/321970859,https://images.cdn-cian.ru/images/2633983674-1...,4.0,4.0,1500.000000,0.0
323570959,cian.ru,-0.479083,-0.071871,0.0,1.0,1.0,160500.0,2025-12-17 08:36:40,Солнечногорск городской округ,Зеленоград — Крюково,21А,НАЗВАНИЕ: Торговая площадь в Московская област...,55.972650,37.099604,https://www.cian.ru/rent/commercial/323570959,https://images.cdn-cian.ru/images/torgovoe-pom...,1.0,1.0,1500.000000,0.0
319937619,cian.ru,1.658292,-0.071871,1.0,0.0,0.0,1226740.0,2025-12-17 08:36:40,Мытищи,Медведково,"ул. Колпакова, 46А","НАЗВАНИЕ: Офис в Московская область, Мытищи ул...",55.925178,37.718300,https://www.cian.ru/rent/commercial/319937619,https://images.cdn-cian.ru/images/2634163777-1...,2.0,6.0,1478.000000,0.0
319936797,cian.ru,-0.322401,-0.071871,1.0,0.0,0.0,236480.0,2025-12-17 08:36:39,Мытищи,Медведково,"ул. Колпакова, 46А","НАЗВАНИЕ: Офис в Московская область, Мытищи ул...",55.925178,37.718300,https://www.cian.ru/rent/commercial/319936797,https://images.cdn-cian.ru/images/2634163921-1...,2.0,6.0,1478.000000,0.0
319938233,cian.ru,2.279106,-0.071871,1.0,0.0,0.0,1537120.0,2025-12-17 08:36:38,Мытищи,Медведково,"ул. Колпакова, 46А","НАЗВАНИЕ: Офис в Московская область, Мытищи ул...",55.925178,37.718300,https://www.cian.ru/rent/commercial/319938233,https://images.cdn-cian.ru/images/2569099478-1...,2.0,6.0,1478.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4750280767,avito.ru,0.730322,-0.871338,1.0,0.0,0.0,736325.0,2025-02-28 14:19:30,Химки,Химки,"Московская обл., Химки, ул. Панфилова, 19с1",НАЗВАНИЕ: Офисное помещение 516.12 кв.м от соб...,55.881490,37.432933,https://www.avito.ru/himki/kommercheskaya_nedv...,https://30.img.avito.st/image/1/1.AlU-sba5rrwI...,1.0,NaN,1426.709940,0.0
4750437026,avito.ru,-0.256772,-0.838334,1.0,0.0,0.0,270000.0,2025-02-28 14:19:23,Котельники,Котельники,"Московская обл., Котельники, Дзержинское ш., 2",НАЗВАНИЕ: Офисное помещение 182.24 кв.м от соб...,55.654477,37.856443,https://www.avito.ru/kotelniki/kommercheskaya_...,https://10.img.avito.st/image/1/1.xz3K9La5a9T8...,5.0,NaN,1481.888035,0.0
4750004434,avito.ru,0.744808,-0.871338,1.0,0.0,0.0,743442.0,2025-02-28 14:19:06,Химки,Химки,"Московская обл., Химки, ул. Панфилова, 19с1",НАЗВАНИЕ: Офисное помещение 521 кв.м от собств...,55.881490,37.432933,https://www.avito.ru/himki/kommercheskaya_nedv...,https://70.img.avito.st/image/1/1.y5athra5Z3-b...,1.0,NaN,1426.952015,0.0
4749580770,avito.ru,-0.107481,NaN,1.0,0.0,0.0,226184.0,2025-02-28 14:18:41,Химки,NaN,"Московская обл., Химки, Авиационная ул., 8",НАЗВАНИЕ: Офисное помещение 232.7 кв.м от собс...,55.983494,37.408939,https://www.avito.ru/himki/kommercheskaya_nedv...,https://10.img.avito.st/image/1/1.DYLprra5oWvf...,2.0,NaN,971.998281,0.0
4937488939,avito.ru,-0.482039,-1.036358,0.0,1.0,0.0,37500.0,2025-02-28 14:10:16,Лобня,Лобня,"Московская обл., Лобня, ул. Ленина, 19к1","НАЗВАНИЕ: Торговое помещение на трафике, 106 м...",56.011696,37.478531,https://www.avito.ru/lobnya/kommercheskaya_ned...,https://70.img.avito.st/image/1/1.gf5Imra5LRd-...,1.0,NaN,4245.283019,0.0

In [13]:
y = df["Цена"].copy()
X = df[["Общая площадь", 'Расстояние до метро, км', 'Вид объекта', 'Тип автора', "Москва?"]].copy()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, stratify=X["Вид объекта"])

In [14]:
X_train["Вид объекта"].value_counts() / X_train.shape[0] * 100

Вид объекта
Торговое / Свободного назначения    68.929586
Офис / Здание                       31.070414
Name: count, dtype: float64

In [15]:
X_test["Вид объекта"].value_counts() / X_test.shape[0] * 100

Вид объекта
Торговое / Свободного назначения    68.930988
Офис / Здание                       31.069012
Name: count, dtype: float64

In [16]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(strategy="constant", fill_value=100, add_indicator=True).fit(X_train[["Расстояние до метро, км"]])
X_train_fillna = si.transform(X_train[["Расстояние до метро, км"]])
X_test_fillna = si.transform(X_test[["Расстояние до метро, км"]])

In [17]:
X_train = pd.concat([X_train.drop("Расстояние до метро, км", axis=1), X_train_fillna], axis=1)
X_test = pd.concat([X_test.drop("Расстояние до метро, км", axis=1), X_test_fillna], axis=1)

X_train.head()

,,Общая площадь,Вид объекта,Тип автора,Москва?,"Расстояние до метро, км","missingindicator_Расстояние до метро, км"
ID на сайте,Источник,,,,,,
316117571,cian.ru,310.0,Торговое / Свободного назначения,Агентство,0.0,9.167,0.0
6125453067051605400,realty.yandex.ru,220.6,Офис / Здание,Агентство,0.0,15.583,0.0
3967137546321426401,realty.yandex.ru,1456.0,Торговое / Свободного назначения,Агентство,0.0,100.000,1.0
323457966,cian.ru,193.0,Офис / Здание,Агентство,0.0,100.000,1.0
6123969892200006544,realty.yandex.ru,320.0,Офис / Здание,Агентство,0.0,27.500,0.0

In [18]:
ct = ColumnTransformer(
    transformers=[
        ("scale", StandardScaler(), ["Общая площадь", "Расстояние до метро, км"]),
        ("onehot", OneHotEncoder(sparse_output=False), ["Вид объекта"]),
        ("ordinal", OrdinalEncoder(), ["Тип автора"]),
    ],
    remainder="passthrough",
    n_jobs=-1,
).set_output(transform="pandas")

ct.fit(X_train)

ColumnTransformer(n_jobs=-1, remainder='passthrough',
                  transformers=[('scale', StandardScaler(),
                                 ['Общая площадь', 'Расстояние до метро, км']),
                                ('onehot', OneHotEncoder(sparse_output=False),
                                 ['Вид объекта']),
                                ('ordinal', OrdinalEncoder(), ['Тип автора'])])

In [19]:
X_train_pre = ct.transform(X_train)
X_test_pre = ct.transform(X_test)

In [20]:
model = LinearRegression().fit(X_train_pre, y_train)

In [21]:
y_pred = model.predict(X_train_pre)
y_test_pred = model.predict(X_test_pre)

In [22]:
r2_score(y_train, y_pred), rmse(y_train, y_pred), mape(y_train, y_pred)

(0.7266569795016193, 222940.481866223, 0.69587320253784)

In [23]:
r2_score(y_test, y_test_pred), rmse(y_test, y_test_pred), mape(y_test, y_test_pred)

(0.7258550433535534, 214867.253747709, 0.7068424189284067)

In [35]:
import sys
import os
two_levels_up = os.path.join(os.getcwd(), "..", "..")
two_levels_up = os.path.abspath(two_levels_up)
sys.path.insert(0, two_levels_up)
import viz