In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv("../data/data_part2.csv")
data = data.sample(20000).copy()

In [2]:
data.head()

,Название,Цена,Дата,Телефон,Оператор,Контактное лицо (автор объявления),Тип автора,Регион,Город,Метро/Район,...,Источник,lat,lng,Персона для контактов,Доп.параметры,URL,Ссылки на картинки,Регион мобильного телефона,Номер подменён,"Расстояние до метро, км"
18190,Производственное помещение в Московская област...,850000,2025-08-04 22:28:32,89153060339,Мобильные ТелеСистемы,Замоскворечье,Агентство,Московская область,Домодедово,Подольск,...,cian.ru,55.450241,37.769756,NaN,Этаж=1|Этажность здания=1|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/318908834,https://images.cdn-cian.ru/images/2530918512-1...,г. Москва и Московская область,да,22.917
18385,Склад (150 м²),150000,2025-08-04 14:21:59,84957615046,не определен,Федор Михайлович (ООО АН Апекс Недвижимость ),Агентство,Московская область,Еганово,Отдых,...,realty.yandex.ru,55.537754,38.025900,NaN,Этаж=1|Этажность здания=1|Тип объявления=Сдам|...,https://realty.ya.ru/offer/2361989377879266127/,https://avatars.mds.yandex.net/get-realty-offe...,не определен,да,26.583
3160,"Склад в Московская область, Раменский муниципа...",400000,2025-10-07 20:27:35,89855121942,Мобильные ТелеСистемы,Отдел аренды коммерческой недвижимости (Универ...,Агентство,Московская область,Раменский муниципальный округ,Домодедовская,...,cian.ru,55.372488,38.145845,NaN,Этаж=1|Этажность здания=1|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/321724768,https://images.cdn-cian.ru/images/2625991318-1...,г. Москва и Московская область,да,неизвестно
10453,"Склад в Московская область, Лобня ул. Горького...",602000,2025-09-07 10:23:42,89856017588,не определен,Игорь Смирнов (Частный маклер),Агентство,Московская область,Лобня,Лобня,...,cian.ru,56.013462,37.503522,NaN,Этаж=1|Этажность здания=2|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/318320605,https://images.cdn-cian.ru/images/sklad-lobnya...,не определен,да,1.5
11200,Помещение свободного назначения в Московская о...,170660,2025-09-03 22:24:00,89390134032,не определен,НДВ,Агентство,Московская область,Мытищи городской округ,Медведково,...,cian.ru,55.984149,37.723394,NaN,Этаж=1|Этажность здания=8|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/317806989,https://images.cdn-cian.ru/images/2496958701-1...,не определен,да,19.25

In [3]:
data.isna().sum()

Название                                  0
Цена                                      0
Дата                                      0
Телефон                                   0
Оператор                                  0
Контактное лицо (автор объявления)      102
Тип автора                                0
Регион                                    0
Город                                     0
Метро/Район                            7186
Адрес                                  3529
Описание                                328
Тип объявления                            0
Категория1                                0
Категория2                                0
ID на сайте                               0
Источник                                  0
lat                                       0
lng                                       0
Персона для контактов                 20000
Доп.параметры                             0
URL                                       0
Ссылки на картинки                      483
Регион мобильного телефона                0
Номер подменён                            0
Расстояние до метро, км                   0
dtype: int64

In [4]:
data = data.dropna(subset=["Цена"])

In [5]:
data.columns

Index(['Название', 'Цена', 'Дата', 'Телефон', 'Оператор',
       'Контактное лицо (автор объявления)', 'Тип автора', 'Регион', 'Город',
       'Метро/Район', 'Адрес', 'Описание', 'Тип объявления', 'Категория1',
       'Категория2', 'ID на сайте', 'Источник', 'lat', 'lng',
       'Персона для контактов', 'Доп.параметры', 'URL', 'Ссылки на картинки',
       'Регион мобильного телефона', 'Номер подменён',
       'Расстояние до метро, км'],
      dtype='object')

In [6]:
data[['Тип объявления', 'Категория1', 'Категория2']].nunique()

Тип объявления    1
Категория1        1
Категория2        1
dtype: int64

In [7]:
data = data.drop([
    'Телефон', 'Оператор', 'Контактное лицо (автор объявления)', 'Персона для контактов',
    'Номер подменён', 'Регион мобильного телефона', 'Регион',
    'Тип объявления', 'Категория1', 'Категория2',
], axis=1)

In [8]:
data.columns

Index(['Название', 'Цена', 'Дата', 'Тип автора', 'Город', 'Метро/Район',
       'Адрес', 'Описание', 'ID на сайте', 'Источник', 'lat', 'lng',
       'Доп.параметры', 'URL', 'Ссылки на картинки',
       'Расстояние до метро, км'],
      dtype='object')

In [9]:
data[['ID на сайте', 'Источник']]

               ID на сайте          Источник
18190            318908834           cian.ru
18385  2361989377879266127  realty.yandex.ru
3160             321724768           cian.ru
10453            318320605           cian.ru
11200            317806989           cian.ru
...                    ...               ...
1614             317911252           cian.ru
10934            320545206           cian.ru
12182            319142621           cian.ru
13912            320017529           cian.ru
18207           7629521184          avito.ru

[20000 rows x 2 columns]

In [10]:
data = data.set_index(['ID на сайте', 'Источник'])

In [11]:
data

,,Название,Цена,Дата,Тип автора,Город,Метро/Район,Адрес,Описание,lat,lng,Доп.параметры,URL,Ссылки на картинки,"Расстояние до метро, км"
ID на сайте,Источник,,,,,,,,,,,,,,
318908834,cian.ru,Производственное помещение в Московская област...,850000,2025-08-04 22:28:32,Агентство,Домодедово,Подольск,"Центральный мкр, ул. Промышленная, 11/5",NaN,55.450241,37.769756,Этаж=1|Этажность здания=1|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/318908834,https://images.cdn-cian.ru/images/2530918512-1...,22.917
2361989377879266127,realty.yandex.ru,Склад (150 м²),150000,2025-08-04 14:21:59,Агентство,Еганово,Отдых,Автодорожная улица,Лот №890789 Предложение от Собственника Напиш...,55.537754,38.025900,Этаж=1|Этажность здания=1|Тип объявления=Сдам|...,https://realty.ya.ru/offer/2361989377879266127/,https://avatars.mds.yandex.net/get-realty-offe...,26.583
321724768,cian.ru,"Склад в Московская область, Раменский муниципа...",400000,2025-10-07 20:27:35,Агентство,Раменский муниципальный округ,Домодедовская,4Б,БЕЗ КОМИССИИ Складской комплекс. Сдаётся под ...,55.372488,38.145845,Этаж=1|Этажность здания=1|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/321724768,https://images.cdn-cian.ru/images/2625991318-1...,неизвестно
318320605,cian.ru,"Склад в Московская область, Лобня ул. Горького...",602000,2025-09-07 10:23:42,Агентство,Лобня,Лобня,"ул. Горького, 104",Сдается в долгосрочную аренду производственно-...,56.013462,37.503522,Этаж=1|Этажность здания=2|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/318320605,https://images.cdn-cian.ru/images/sklad-lobnya...,1.5
317806989,cian.ru,Помещение свободного назначения в Московская о...,170660,2025-09-03 22:24:00,Агентство,Мытищи городской округ,Медведково,"ул. Ильинского, 8",Лот 46894958. Продажа коммерческого помещения ...,55.984149,37.723394,Этаж=1|Этажность здания=8|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/317806989,https://images.cdn-cian.ru/images/2496958701-1...,19.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317911252,cian.ru,"Офис в Московская область, Химки городской окр...",76440,2025-10-13 00:21:17,Агентство,Химки городской округ,Новоподрезково,"ул. Аэропортовская, с2",Бизнес-центр Sherland класса A Площадь: 91 м...,55.977793,37.372126,Этаж=2|Этажность здания=9|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/317911252,https://images.cdn-cian.ru/images/2499534218-1...,11
320545206,cian.ru,Помещение свободного назначения в Московская о...,25000,2025-09-05 12:24:10,Частное лицо (фильтр),Ленинский городской округ,Бутово,"ул. Лесная, 2",Помещения 30м² | Ремонт | Первая линия |Место ...,55.538107,37.615524,Этаж=1|Этажность здания=20|Тип объявления=Сдам...,https://www.cian.ru/rent/commercial/320545206,https://images.cdn-cian.ru/images/nezhiloe-pom...,4.583
319142621,cian.ru,Помещение свободного назначения в Московская о...,222360,2025-08-31 06:24:05,Частное лицо,Мытищи,Медведково,"Силикатная ул., 19",Индустриальный парк ЭЛМА Мытищи предлагает в...,55.932021,37.776727,Этаж=9|Этажность здания=10|Тип объявления=Сдам...,https://www.cian.ru/rent/commercial/319142621,https://images.cdn-cian.ru/images/nezhiloe-pom...,16.5
320017529,cian.ru,"Торговая площадь в Московская область, Подольс...",228000,2025-08-21 04:35:28,Агентство,Подольск,Подольск,"Вокзальная пл., 8",Объект 44 Предлагается в аренду помещение своб...,55.432807,37.565129,Этаж=2|Этажность здания=3|Тип объявления=Сдам|...,https://www.cian.ru/rent/commercial/320017529,https://images.cdn-cian.ru/images/2571005077-1...,0.083
7629521184,avito.ru,Офисное помещение 33 кв.м от собственника,39600,2025-08-04 21:43:02,Агентство,Химки,Молжаниново,"Московская обл., Химки, мкр-н Новогорск, Зареч...",Cдаeтcя в аpенду просторный oфис 33 кв.м. Cоcт...,55.904422,37.360492,Этаж=2|Тип объявления=Сдам|Вид объекта=Офисное...,https://www.avito.ru/himki/kommercheskaya_nedv...,https://00.img.avito.st/image/1/1.kcMkn7a5PSoS...,2.5999999046326

In [12]:
# data.loc[(313517556, "cian.ru")]

In [13]:
data[["Название", "Описание"]]

,,Название,Описание
ID на сайте,Источник,,
318908834,cian.ru,Производственное помещение в Московская област...,NaN
2361989377879266127,realty.yandex.ru,Склад (150 м²),Лот №890789 Предложение от Собственника Напиш...
321724768,cian.ru,"Склад в Московская область, Раменский муниципа...",БЕЗ КОМИССИИ Складской комплекс. Сдаётся под ...
318320605,cian.ru,"Склад в Московская область, Лобня ул. Горького...",Сдается в долгосрочную аренду производственно-...
317806989,cian.ru,Помещение свободного назначения в Московская о...,Лот 46894958. Продажа коммерческого помещения ...
...,...,...,...
317911252,cian.ru,"Офис в Московская область, Химки городской окр...",Бизнес-центр Sherland класса A Площадь: 91 м...
320545206,cian.ru,Помещение свободного назначения в Московская о...,Помещения 30м² | Ремонт | Первая линия |Место ...
319142621,cian.ru,Помещение свободного назначения в Московская о...,Индустриальный парк ЭЛМА Мытищи предлагает в...
320017529,cian.ru,"Торговая площадь в Московская область, Подольс...",Объект 44 Предлагается в аренду помещение своб...
7629521184,avito.ru,Офисное помещение 33 кв.м от собственника,Cдаeтcя в аpенду просторный oфис 33 кв.м. Cоcт...

In [14]:
data.loc[:, ["Название", "Описание"]]

,,Название,Описание
ID на сайте,Источник,,
318908834,cian.ru,Производственное помещение в Московская област...,NaN
2361989377879266127,realty.yandex.ru,Склад (150 м²),Лот №890789 Предложение от Собственника Напиш...
321724768,cian.ru,"Склад в Московская область, Раменский муниципа...",БЕЗ КОМИССИИ Складской комплекс. Сдаётся под ...
318320605,cian.ru,"Склад в Московская область, Лобня ул. Горького...",Сдается в долгосрочную аренду производственно-...
317806989,cian.ru,Помещение свободного назначения в Московская о...,Лот 46894958. Продажа коммерческого помещения ...
...,...,...,...
317911252,cian.ru,"Офис в Московская область, Химки городской окр...",Бизнес-центр Sherland класса A Площадь: 91 м...
320545206,cian.ru,Помещение свободного назначения в Московская о...,Помещения 30м² | Ремонт | Первая линия |Место ...
319142621,cian.ru,Помещение свободного назначения в Московская о...,Индустриальный парк ЭЛМА Мытищи предлагает в...
320017529,cian.ru,"Торговая площадь в Московская область, Подольс...",Объект 44 Предлагается в аренду помещение своб...
7629521184,avito.ru,Офисное помещение 33 кв.м от собственника,Cдаeтcя в аpенду просторный oфис 33 кв.м. Cоcт...

In [15]:
# data.loc[
#     (313517556, "cian.ru"),
#     "Описание",
# ]

In [16]:
data["Название"] = data["Название"].fillna("").astype(str)
data["Описание"] = data["Описание"].fillna("").astype(str)
data["Описание"] = "НАЗВАНИЕ: " + data["Название"] + "\n\n" + "ОПИСАНИЕ: " + data["Описание"]

In [17]:
# print(data.loc[
#     (313517556, "cian.ru"),
#     "Описание",
# ])

In [18]:
data = data.drop("Название", axis=1)

In [19]:
data["Доп.параметры"].iloc[10]

'Ед. измерения площади=сот.|Категория=Участок поселений|Тип объявления=Сдам|Вид объекта=Коммерческая земля|Общая площадь=10.18'

In [20]:
def parse_parameters(v):
    return dict(
        pair.split("=")
        for pair in v.split("|")
    )

parse_parameters(data["Доп.параметры"].iloc[10])

{'Ед. измерения площади': 'сот.',
 'Категория': 'Участок поселений',
 'Тип объявления': 'Сдам',
 'Вид объекта': 'Коммерческая земля',
 'Общая площадь': '10.18'}

In [21]:
_ = data["Доп.параметры"].apply(parse_parameters)
params_parsed = pd.json_normalize(_)
params_parsed.index = data.index
params_parsed

,,Этаж,Этажность здания,Тип объявления,Вид объекта,Общая площадь,Ед. измерения площади,Категория,Класс здания
ID на сайте,Источник,,,,,,,,
318908834,cian.ru,1,1,Сдам,Производственное помещение,850,NaN,NaN,NaN
2361989377879266127,realty.yandex.ru,1,1,Сдам,Складское помещение,150,NaN,NaN,NaN
321724768,cian.ru,1,1,Сдам,Складское помещение,1000,NaN,NaN,NaN
318320605,cian.ru,1,2,Сдам,Складское помещение,860,NaN,NaN,NaN
317806989,cian.ru,1,8,Сдам,Помещение свободного назначения,64,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
317911252,cian.ru,2,9,Сдам,Офисное помещение,91,NaN,NaN,NaN
320545206,cian.ru,1,20,Сдам,Помещение свободного назначения,10,NaN,NaN,NaN
319142621,cian.ru,9,10,Сдам,Помещение свободного назначения,170,NaN,NaN,NaN
320017529,cian.ru,2,3,Сдам,Торговое помещение,120,NaN,NaN,NaN
7629521184,avito.ru,2,NaN,Сдам,Офисное помещение,33,NaN,NaN,B

In [22]:
params_parsed.isna().sum() / params_parsed.shape[0] * 100

Этаж                     20.205
Этажность здания         22.480
Тип объявления            0.000
Вид объекта               0.160
Общая площадь             0.025
Ед. измерения площади    81.765
Категория                82.725
Класс здания             99.115
dtype: float64

In [23]:
params_parsed.nunique()

Этаж                       29
Этажность здания           41
Тип объявления              1
Вид объекта                 8
Общая площадь            3748
Ед. измерения площади       2
Категория                   3
Класс здания                4
dtype: int64

In [24]:
params_parsed["Ед. измерения площади"].unique()

array([nan, 'сот.', 'га.'], dtype=object)

In [25]:
params_parsed = params_parsed.drop(["Класс здания", "Тип объявления"], axis=1)

In [26]:
data = pd.concat(
    [
        data.drop("Доп.параметры", axis=1),
        params_parsed
    ],
    axis=1
)
data

,,Цена,Дата,Тип автора,Город,Метро/Район,Адрес,Описание,lat,lng,URL,Ссылки на картинки,"Расстояние до метро, км",Этаж,Этажность здания,Вид объекта,Общая площадь,Ед. измерения площади,Категория
ID на сайте,Источник,,,,,,,,,,,,,,,,,,
318908834,cian.ru,850000,2025-08-04 22:28:32,Агентство,Домодедово,Подольск,"Центральный мкр, ул. Промышленная, 11/5",НАЗВАНИЕ: Производственное помещение в Московс...,55.450241,37.769756,https://www.cian.ru/rent/commercial/318908834,https://images.cdn-cian.ru/images/2530918512-1...,22.917,1,1,Производственное помещение,850,NaN,NaN
2361989377879266127,realty.yandex.ru,150000,2025-08-04 14:21:59,Агентство,Еганово,Отдых,Автодорожная улица,НАЗВАНИЕ: Склад (150 м²)\n\nОПИСАНИЕ: Лот №890...,55.537754,38.025900,https://realty.ya.ru/offer/2361989377879266127/,https://avatars.mds.yandex.net/get-realty-offe...,26.583,1,1,Складское помещение,150,NaN,NaN
321724768,cian.ru,400000,2025-10-07 20:27:35,Агентство,Раменский муниципальный округ,Домодедовская,4Б,"НАЗВАНИЕ: Склад в Московская область, Раменски...",55.372488,38.145845,https://www.cian.ru/rent/commercial/321724768,https://images.cdn-cian.ru/images/2625991318-1...,неизвестно,1,1,Складское помещение,1000,NaN,NaN
318320605,cian.ru,602000,2025-09-07 10:23:42,Агентство,Лобня,Лобня,"ул. Горького, 104","НАЗВАНИЕ: Склад в Московская область, Лобня ул...",56.013462,37.503522,https://www.cian.ru/rent/commercial/318320605,https://images.cdn-cian.ru/images/sklad-lobnya...,1.5,1,2,Складское помещение,860,NaN,NaN
317806989,cian.ru,170660,2025-09-03 22:24:00,Агентство,Мытищи городской округ,Медведково,"ул. Ильинского, 8",НАЗВАНИЕ: Помещение свободного назначения в Мо...,55.984149,37.723394,https://www.cian.ru/rent/commercial/317806989,https://images.cdn-cian.ru/images/2496958701-1...,19.25,1,8,Помещение свободного назначения,64,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317911252,cian.ru,76440,2025-10-13 00:21:17,Агентство,Химки городской округ,Новоподрезково,"ул. Аэропортовская, с2","НАЗВАНИЕ: Офис в Московская область, Химки гор...",55.977793,37.372126,https://www.cian.ru/rent/commercial/317911252,https://images.cdn-cian.ru/images/2499534218-1...,11,2,9,Офисное помещение,91,NaN,NaN
320545206,cian.ru,25000,2025-09-05 12:24:10,Частное лицо (фильтр),Ленинский городской округ,Бутово,"ул. Лесная, 2",НАЗВАНИЕ: Помещение свободного назначения в Мо...,55.538107,37.615524,https://www.cian.ru/rent/commercial/320545206,https://images.cdn-cian.ru/images/nezhiloe-pom...,4.583,1,20,Помещение свободного назначения,10,NaN,NaN
319142621,cian.ru,222360,2025-08-31 06:24:05,Частное лицо,Мытищи,Медведково,"Силикатная ул., 19",НАЗВАНИЕ: Помещение свободного назначения в Мо...,55.932021,37.776727,https://www.cian.ru/rent/commercial/319142621,https://images.cdn-cian.ru/images/nezhiloe-pom...,16.5,9,10,Помещение свободного назначения,170,NaN,NaN
320017529,cian.ru,228000,2025-08-21 04:35:28,Агентство,Подольск,Подольск,"Вокзальная пл., 8",НАЗВАНИЕ: Торговая площадь в Московская област...,55.432807,37.565129,https://www.cian.ru/rent/commercial/320017529,https://images.cdn-cian.ru/images/2571005077-1...,0.083,2,3,Торговое помещение,120,NaN,NaN
7629521184,avito.ru,39600,2025-08-04 21:43:02,Агентство,Химки,Молжаниново,"Московская обл., Химки, мкр-н Новогорск, Зареч...",НАЗВАНИЕ: Офисное помещение 33 кв.м от собстве...,55.904422,37.360492,https://www.avito.ru/himki/kommercheskaya_nedv...,https://00.img.avito.st/image/1/1.kcMkn7a5PSoS...,2.5999999046326,2,NaN,Офисное помещение,33,NaN,NaN

In [27]:
data.dtypes

Цена                         int64
Дата                        object
Тип автора                  object
Город                       object
Метро/Район                 object
Адрес                       object
Описание                    object
lat                        float64
lng                        float64
URL                         object
Ссылки на картинки          object
Расстояние до метро, км     object
Этаж                        object
Этажность здания            object
Вид объекта                 object
Общая площадь               object
Ед. измерения площади       object
Категория                   object
dtype: object

In [28]:
data["Категория"].unique()

array([nan, 'Участок поселений', 'Промназначение', 'Сельхозназначение'],
      dtype=object)

In [29]:
data["Дата"] = pd.to_datetime(data["Дата"])
data["Дата"]

ID на сайте          Источник
318908834            cian.ru            2025-08-04 22:28:32
2361989377879266127  realty.yandex.ru   2025-08-04 14:21:59
321724768            cian.ru            2025-10-07 20:27:35
318320605            cian.ru            2025-09-07 10:23:42
317806989            cian.ru            2025-09-03 22:24:00
                                                ...
317911252            cian.ru            2025-10-13 00:21:17
320545206            cian.ru            2025-09-05 12:24:10
319142621            cian.ru            2025-08-31 06:24:05
320017529            cian.ru            2025-08-21 04:35:28
7629521184           avito.ru           2025-08-04 21:43:02
Name: Дата, Length: 20000, dtype: datetime64[ns]

In [30]:
data["Дата"].dt.dayofyear

ID на сайте          Источник
318908834            cian.ru             216
2361989377879266127  realty.yandex.ru    216
321724768            cian.ru             280
318320605            cian.ru             250
317806989            cian.ru             246
                                        ...
317911252            cian.ru             286
320545206            cian.ru             248
319142621            cian.ru             243
320017529            cian.ru             233
7629521184           avito.ru            216
Name: Дата, Length: 20000, dtype: int32

In [31]:
# data[[
#     "Расстояние до метро, км",
#     "Этаж",
#     "Общая площадь",
#     "Этажность здания",
# ]].astype(float)

In [32]:
data["Расстояние до метро, км"]

ID на сайте          Источник
318908834            cian.ru                      22.917
2361989377879266127  realty.yandex.ru             26.583
321724768            cian.ru                  неизвестно
318320605            cian.ru                         1.5
317806989            cian.ru                       19.25
                                              ...
317911252            cian.ru                          11
320545206            cian.ru                       4.583
319142621            cian.ru                        16.5
320017529            cian.ru                       0.083
7629521184           avito.ru            2.5999999046326
Name: Расстояние до метро, км, Length: 20000, dtype: object

In [33]:
data["Расстояние до метро, км"] = data["Расстояние до метро, км"].replace({"неизвестно": np.nan}).values

In [34]:
data[[
    "Расстояние до метро, км",
    "Этаж",
    "Общая площадь",
    "Этажность здания",
]] = data[[
    "Расстояние до метро, км",
    "Этаж",
    "Общая площадь",
    "Этажность здания",
]].astype(float)

In [35]:
data.isna().sum()

Цена                           0
Дата                           0
Тип автора                     0
Город                          0
Метро/Район                 7186
Адрес                       3529
Описание                       0
lat                            0
lng                            0
URL                            0
Ссылки на картинки           483
Расстояние до метро, км     7720
Этаж                        4041
Этажность здания            4496
Вид объекта                   32
Общая площадь                  5
Ед. измерения площади      16353
Категория                  16545
dtype: int64

In [36]:
data["Ед. измерения площади"].value_counts()

Ед. измерения площади
сот.    3577
га.       70
Name: count, dtype: int64

In [37]:
data.dropna(subset=["Общая площадь", "Ед. измерения площади"])[["Общая площадь", "Ед. измерения площади"]]

                      Общая площадь Ед. измерения площади
ID на сайте Источник
321330443   cian.ru            9.26                  сот.
320525269   cian.ru           12.04                  сот.
317494331   cian.ru           40.00                  сот.
316345216   cian.ru           10.18                  сот.
322339061   cian.ru            5.00                   га.
...                             ...                   ...
319109158   cian.ru            8.13                  сот.
322249107   cian.ru           40.00                  сот.
319366823   cian.ru           15.05                  сот.
321090308   cian.ru            7.22                  сот.
321090161   cian.ru           10.20                  сот.

[3647 rows x 2 columns]

In [38]:
data[["Общая площадь", "Ед. измерения площади"]].dropna()

                      Общая площадь Ед. измерения площади
ID на сайте Источник
321330443   cian.ru            9.26                  сот.
320525269   cian.ru           12.04                  сот.
317494331   cian.ru           40.00                  сот.
316345216   cian.ru           10.18                  сот.
322339061   cian.ru            5.00                   га.
...                             ...                   ...
319109158   cian.ru            8.13                  сот.
322249107   cian.ru           40.00                  сот.
319366823   cian.ru           15.05                  сот.
321090308   cian.ru            7.22                  сот.
321090161   cian.ru           10.20                  сот.

[3647 rows x 2 columns]

In [39]:
data[["Общая площадь", "Ед. измерения площади"]].sample(5)

                      Общая площадь Ед. измерения площади
ID на сайте Источник
321646505   cian.ru           400.0                   NaN
321706285   cian.ru          1426.0                   NaN
320292058   cian.ru           309.0                   NaN
321970284   cian.ru           124.0                   NaN
321413588   cian.ru            35.0                   NaN

In [40]:
data.loc[
    data["Ед. измерения площади"] == "сот.",
    "Общая площадь"
] *= 100

data.loc[
    data["Ед. измерения площади"] == "га.",
    "Общая площадь"
] *= 10000

In [41]:
data = data.drop("Ед. измерения площади", axis=1)

In [42]:
data.to_csv("../data/data_part2_transform.csv")

In [43]:
data.head()

,,Цена,Дата,Тип автора,Город,Метро/Район,Адрес,Описание,lat,lng,URL,Ссылки на картинки,"Расстояние до метро, км",Этаж,Этажность здания,Вид объекта,Общая площадь,Категория
ID на сайте,Источник,,,,,,,,,,,,,,,,,
318908834,cian.ru,850000,2025-08-04 22:28:32,Агентство,Домодедово,Подольск,"Центральный мкр, ул. Промышленная, 11/5",НАЗВАНИЕ: Производственное помещение в Московс...,55.450241,37.769756,https://www.cian.ru/rent/commercial/318908834,https://images.cdn-cian.ru/images/2530918512-1...,22.917,1.0,1.0,Производственное помещение,850.0,NaN
2361989377879266127,realty.yandex.ru,150000,2025-08-04 14:21:59,Агентство,Еганово,Отдых,Автодорожная улица,НАЗВАНИЕ: Склад (150 м²)\n\nОПИСАНИЕ: Лот №890...,55.537754,38.025900,https://realty.ya.ru/offer/2361989377879266127/,https://avatars.mds.yandex.net/get-realty-offe...,26.583,1.0,1.0,Складское помещение,150.0,NaN
321724768,cian.ru,400000,2025-10-07 20:27:35,Агентство,Раменский муниципальный округ,Домодедовская,4Б,"НАЗВАНИЕ: Склад в Московская область, Раменски...",55.372488,38.145845,https://www.cian.ru/rent/commercial/321724768,https://images.cdn-cian.ru/images/2625991318-1...,NaN,1.0,1.0,Складское помещение,1000.0,NaN
318320605,cian.ru,602000,2025-09-07 10:23:42,Агентство,Лобня,Лобня,"ул. Горького, 104","НАЗВАНИЕ: Склад в Московская область, Лобня ул...",56.013462,37.503522,https://www.cian.ru/rent/commercial/318320605,https://images.cdn-cian.ru/images/sklad-lobnya...,1.500,1.0,2.0,Складское помещение,860.0,NaN
317806989,cian.ru,170660,2025-09-03 22:24:00,Агентство,Мытищи городской округ,Медведково,"ул. Ильинского, 8",НАЗВАНИЕ: Помещение свободного назначения в Мо...,55.984149,37.723394,https://www.cian.ru/rent/commercial/317806989,https://images.cdn-cian.ru/images/2496958701-1...,19.250,1.0,8.0,Помещение свободного назначения,64.0,NaN